/**
 * Flags provided by Flag Icons https://github.com/lipis/flag-icons/tree/main
 */
export const currencyOptions = [
  {label: 'AED', properties:{name:'United Arab Emirates dirham', flag:'ae'}, value: 'AED'},
  {label: 'AFN', properties:{name:'Afghan afghani', flag:'af'}, value: 'AFN'},
  {label: 'ALL', properties:{name:'Albanian lek', flag:'al'}, value: 'ALL'},
  {label: 'AMD', properties:{name:'Armenian dram', flag:'am'}, value: 'AMD'},
  {label: 'AOA', properties:{name:'Angolan kwanza', flag:'ao'}, value: 'AOA'},
  {label: 'ARS', properties:{name:'Argentine peso', flag:'ar'}, value: 'ARS'},
  {label: 'AUD', properties:{name:'Australian dollar', flag:'au'}, value: 'AUD'},
  {label: 'AWG', properties:{name:'Aruban florin', flag:'aw'}, value: 'AWG'},
  {label: 'AZN', properties:{name:'Azerbaijani manat', flag:'az'}, value: 'AZN'},
  {label: 'BAM', properties:{name:'Bosnia and Herzegovina convertible mark', flag:'ba'}, value: 'BAM'},
  {label: 'BBD', properties:{name:'Barbados dollar', flag:'bb'}, value: 'BBD'},
  {label: 'BDT', properties:{name:'Bangladeshi taka', flag:'bd'}, value: 'BDT'},
  {label: 'BHD', properties:{name:'Bahraini dinar', flag:'bh'}, value: 'BHD'},
  {label: 'BIF', properties:{name:'Burundian franc', flag:'bi'}, value: 'BIF'},
  {label: 'BMD', properties:{name:'Bermudian dollar', flag:'bm'}, value: 'BMD'},
  {label: 'BND', properties:{name:'Brunei dollar', flag:'bn'}, value: 'BND'},
  {label: 'BOB', properties:{name:'Boliviano', flag:'bo'}, value: 'BOB'},
  {label: 'BOV', properties:{name:'Bolivian Mvdol (funds code)', flag:'bo'}, value: 'BOV'},
  {label: 'BRL', properties:{name:'Brazilian real', flag:'br'}, value: 'BRL'},
  {label: 'BSD', properties:{name:'Bahamian dollar', flag:'bs'}, value: 'BSD'},
  {label: 'BTN', properties:{name:'Bhutanese ngultrum', flag:'bh'}, value: 'BTN'},
  {label: 'BWP', properties:{name:'Botswana pula', flag:'bw'}, value: 'BWP'},
  {label: 'BYN', properties:{name:'Belarusian ruble', flag:'by'}, value: 'BYN'},
  {label: 'BZD', properties:{name:'Belize dollar', flag:'bz'}, value: 'BZD'},
  {label: 'CAD', properties:{name:'Canadian dollar', flag:'ca'}, value: 'CAD'},
  {label: 'CDF', properties:{name:'Congolese franc', flag:'cd'}, value: 'CDF'},
  {label: 'CHF', properties:{name:'Swiss franc', flag:'ch'}, value: 'CHF'},
  {label: 'CLP', properties:{name:'Chilean peso', flag:'cl'}, value: 'CLP'},
  {label: 'CNY', properties:{name:'Renminbi', flag:'cn'}, value: 'CNY'},
  {label: 'COP', properties:{name:'Colombian peso', flag:'co'}, value: 'COP'},
  {label: 'CRC', properties:{name:'Costa Rican colon', flag:'cr'}, value: 'CRC'},
  {label: 'CUP', properties:{name:'Cuban peso', flag:'cu'}, value: 'CUP'},
  {label: 'CVE', properties:{name:'Cape Verdean escudo', flag:'cv'}, value: 'CVE'},
  {label: 'CZK', properties:{name:'Czech koruna', flag:'cz'}, value: 'CZK'},
  {label: 'DJF', properties:{name:'Djiboutian franc', flag:'dj'}, value: 'DJF'},
  {label: 'DKK', properties:{name:'Danish krone', flag:'dk'}, value: 'DKK'},
  {label: 'DOP', properties:{name:'Dominican peso', flag:'dm'}, value: 'DOP'},
  {label: 'DZD', properties:{name:'Algerian dinar', flag:'dz'}, value: 'DZD'},
  {label: 'EGP', properties:{name:'Egyptian pound', flag:'eg'}, value: 'EGP'},
  {label: 'ERN', properties:{name:'Eritrean nakfa', flag:'er'}, value: 'ERN'},
  {label: 'ETB', properties:{name:'Ethiopian birr', flag:'et'}, value: 'ETB'},
  {label: 'EUR', properties:{name:'Euro', flag:'eu'}, value: 'EUR'},
  {label: 'FJD', properties:{name:'Fiji dollar', flag:'fj'}, value: 'FJD'},
  {label: 'FKP', properties:{name:'Falkland Islands pound', flag:'fk'}, value: 'FKP'},
  {label: 'GBP', properties:{name:'Pound sterling', flag:'gb'}, value: 'GBP'},
  {label: 'GEL', properties:{name:'Georgian lari', flag:'ge'}, value: 'GEL'},
  {label: 'GHS', properties:{name:'Ghanaian cedi', flag:'gh'}, value: 'GHS'},
  {label: 'GIP', properties:{name:'Gibraltar pound', flag:'gi'}, value: 'GIP'},
  {label: 'GMD', properties:{name:'Gambian dalasi', flag:'gm'}, value: 'GMD'},
  {label: 'GNF', properties:{name:'Guinean franc', flag:'gn'}, value: 'GNF'},
  {label: 'GTQ', properties:{name:'Guatemalan quetzal', flag:'gt'}, value: 'GTQ'},
  {label: 'GYD', properties:{name:'Guyanese dollar', flag:'gy'}, value: 'GYD'},
  {label: 'HKD', properties:{name:'Hong Kong dollar', flag:'hk'}, value: 'HKD'},
  {label: 'HNL', properties:{name:'Honduran lempira', flag:'hn'}, value: 'HNL'},
  {label: 'HTG', properties:{name:'Haitian gourde', flag:'ht'}, value: 'HTG'},
  {label: 'HUF', properties:{name:'Hungarian forint', flag:'hu'}, value: 'HUF'},
  {label: 'IDR', properties:{name:'Indonesian rupiah', flag:'id'}, value: 'IDR'},
  {label: 'ILS', properties:{name:'Israeli new shekel', flag:'il'}, value: 'ILS'},
  {label: 'INR', properties:{name:'Indian rupee', flag:'in'}, value: 'INR'},
  {label: 'IQD', properties:{name:'Iraqi dinar', flag:'iq'}, value: 'IQD'},
  {label: 'IRR', properties:{name:'Iranian rial', flag:'ir'}, value: 'IRR'},
  {label: 'ISK', properties:{name:'Icelandic króna', flag:'is'}, value: 'ISK'},
  {label: 'JMD', properties:{name:'Jamaican dollar', flag:'jm'}, value: 'JMD'},
  {label: 'JOD', properties:{name:'Jordanian dinar', flag:'jo'}, value: 'JOD'},
  {label: 'JPY', properties:{name:'Japanese yen', flag:'jp'}, value: 'JPY'},
  {label: 'KES', properties:{name:'Kenyan shilling', flag:'ke'}, value: 'KES'},
  {label: 'KGS', properties:{name:'Kyrgyzstani som', flag:'kg'}, value: 'KGS'},
  {label: 'KHR', properties:{name:'Cambodian riel', flag:'kh'}, value: 'KHR'},
  {label: 'KMF', properties:{name:'Comoro franc', flag:'km'}, value: 'KMF'},
  {label: 'KPW', properties:{name:'North Korean won', flag:'kp'}, value: 'KPW'},
  {label: 'KRW', properties:{name:'South Korean won', flag:'kr'}, value: 'KRW'},
  {label: 'KWD', properties:{name:'Kuwaiti dinar', flag:'kw'}, value: 'KWD'},
  {label: 'KYD', properties:{name:'Cayman Islands dollar', flag:'ky'}, value: 'KYD'},
  {label: 'KZT', properties:{name:'Kazakhstani tenge', flag:'kz'}, value: 'KZT'},
  {label: 'LAK', properties:{name:'Lao kip', flag:'la'}, value: 'LAK'},
  {label: 'LBP', properties:{name:'Lebanese pound', flag:'lb'}, value: 'LBP'},
  {label: 'LKR', properties:{name:'Sri Lankan rupee', flag:'lk'}, value: 'LKR'},
  {label: 'LRD', properties:{name:'Liberian dollar', flag:'lr'}, value: 'LRD'},
  {label: 'LSL', properties:{name:'Lesotho loti', flag:'ls'}, value: 'LSL'},
  {label: 'LYD', properties:{name:'Libyan dinar', flag:'ly'}, value: 'LYD'},
  {label: 'MAD', properties:{name:'Moroccan dirham', flag:'ma'}, value: 'MAD'},
  {label: 'MDL', properties:{name:'Moldovan leu', flag:'md'}, value: 'MDL'},
  {label: 'MGA', properties:{name:'Malagasy ariary', flag:'my'}, value: 'MGA'},
  {label: 'MKD', properties:{name:'Macedonian denar', flag:'mk'}, value: 'MKD'},
  {label: 'MMK', properties:{name:'Myanmar kyat', flag:'mm'}, value: 'MMK'},
  {label: 'MNT', properties:{name:'Mongolian tögrög', flag:'mn'}, value: 'MNT'},
  {label: 'MOP', properties:{name:'Macanese pataca', flag:'mo'}, value: 'MOP'},
  {label: 'MRU', properties:{name:'Mauritanian ouguiya', flag:'mr'}, value: 'MRU'},
  {label: 'MUR', properties:{name:'Mauritian rupee', flag:'mu'}, value: 'MUR'},
  {label: 'MVR', properties:{name:'Maldivian rufiyaa', flag:'mv'}, value: 'MVR'},
  {label: 'MWK', properties:{name:'Malawian kwacha', flag:'mw'}, value: 'MWK'},
  {label: 'MXN', properties:{name:'Mexican peso', flag:'mx'}, value: 'MXN'},
  {label: 'MYR', properties:{name:'Malaysian ringgit', flag:'my'}, value: 'MYR'},
  {label: 'MZN', properties:{name:'Mozambican metical', flag:'mz'}, value: 'MZN'},
  {label: 'NAD', properties:{name:'Namibian dollar', flag:'na'}, value: 'NAD'},
  {label: 'NGN', properties:{name:'Nigerian naira', flag:'ng'}, value: 'NGN'},
  {label: 'NIO', properties:{name:'Nicaraguan córdoba', flag:'ni'}, value: 'NIO'},
  {label: 'NOK', properties:{name:'Norwegian krone', flag:'no'}, value: 'NOK'},
  {label: 'NPR', properties:{name:'Nepalese rupee', flag:'np'}, value: 'NPR'},
  {label: 'NZD', properties:{name:'New Zealand dollar', flag:'nz'}, value: 'NZD'},
  {label: 'OMR', properties:{name:'Omani rial', flag:'om'}, value: 'OMR'},
  {label: 'PAB', properties:{name:'Panamanian balboa', flag:'pa'}, value: 'PAB'},
  {label: 'PEN', properties:{name:'Peruvian sol', flag:'pe'}, value: 'PEN'},
  {label: 'PGK', properties:{name:'Papua New Guinean kina', flag:'pg'}, value: 'PGK'},
  {label: 'PHP', properties:{name:'Philippine peso', flag:'ph'}, value: 'PHP'},
  {label: 'PKR', properties:{name:'Pakistani rupee', flag:'pa'}, value: 'PKR'},
  {label: 'PLN', properties:{name:'Polish złoty', flag:'pl'}, value: 'PLN'},
  {label: 'PYG', properties:{name:'Paraguayan guaraní', flag:'py'}, value: 'PYG'},
  {label: 'QAR', properties:{name:'Qatari riyal', flag:'qa'}, value: 'QAR'},
  {label: 'RON', properties:{name:'Romanian leu', flag:'ro'}, value: 'RON'},
  {label: 'RSD', properties:{name:'Serbian dinar', flag:'rs'}, value: 'RSD'},
  {label: 'RUB', properties:{name:'Russian ruble', flag:'ru'}, value: 'RUB'},
  {label: 'RWF', properties:{name:'Rwandan franc', flag:'rw'}, value: 'RWF'},
  {label: 'SAR', properties:{name:'Saudi riyal', flag:'sa'}, value: 'SAR'},
  {label: 'SBD', properties:{name:'Solomon Islands dollar', flag:'sb'}, value: 'SBD'},
  {label: 'SCR', properties:{name:'Seychelles rupee', flag:'sc'}, value: 'SCR'},
  {label: 'SDG', properties:{name:'Sudanese pound', flag:'sd'}, value: 'SDG'},
  {label: 'SEK', properties:{name:'Swedish krona', flag:'se'}, value: 'SEK'},
  {label: 'SGD', properties:{name:'Singapore dollar', flag:'sg'}, value: 'SGD'},
  {label: 'SHP', properties:{name:'Saint Helena pound', flag:'sh'}, value: 'SHP'},
  {label: 'SLE', properties:{name:'Sierra Leonean leone (new leone)[12][13][14]', flag:'sl'}, value: 'SLE'},
  {label: 'SOS', properties:{name:'Somalian shilling', flag:'so'}, value: 'SOS'},
  {label: 'SRD', properties:{name:'Surinamese dollar', flag:'sr'}, value: 'SRD'},
  {label: 'SSP', properties:{name:'South Sudanese pound', flag:'ss'}, value: 'SSP'},
  {label: 'STN', properties:{name:'São Tomé and Príncipe dobra', flag:'st'}, value: 'STN'},
  {label: 'SVC', properties:{name:'Salvadoran colón', flag:'sv'}, value: 'SVC'},
  {label: 'SYP', properties:{name:'Syrian pound', flag:'sy'}, value: 'SYP'},
  {label: 'SZL', properties:{name:'Swazi lilangeni', flag:'sz'}, value: 'SZL'},
  {label: 'THB', properties:{name:'Thai baht', flag:'th'}, value: 'THB'},
  {label: 'TJS', properties:{name:'Tajikistani somoni', flag:'tj'}, value: 'TJS'},
  {label: 'TMT', properties:{name:'Turkmenistan manat', flag:'tm'}, value: 'TMT'},
  {label: 'TND', properties:{name:'Tunisian dinar', flag:'tn'}, value: 'TND'},
  {label: 'TOP', properties:{name:'Tongan paʻanga', flag:'to'}, value: 'TOP'},
  {label: 'TRY', properties:{name:'Turkish lira', flag:'tr'}, value: 'TRY'},
  {label: 'TTD', properties:{name:'Trinidad and Tobago dollar', flag:'tt'}, value: 'TTD'},
  {label: 'TWD', properties:{name:'New Taiwan dollar', flag:'tw'}, value: 'TWD'},
  {label: 'TZS', properties:{name:'Tanzanian shilling', flag:'tz'}, value: 'TZS'},
  {label: 'UAH', properties:{name:'Ukrainian hryvnia', flag:'ua'}, value: 'UAH'},
  {label: 'UGX', properties:{name:'Ugandan shilling', flag:'ug'}, value: 'UGX'},
  {label: 'USD', properties:{name:'United States dollar', flag:'us'}, value: 'USD'},
  {label: 'UYU', properties:{name:'Uruguayan peso', flag:'uy'}, value: 'UYU'},
  {label: 'UZS', properties:{name:'Uzbekistani sum', flag:'uz'}, value: 'UZS'},
  {label: 'VED', properties:{name:'Venezuelan digital bolívar', flag:'ve'}, value: 'VED'},
  {label: 'VES', properties:{name:'Venezuelan sovereign bolívar', flag:'ve'}, value: 'VES'},
  {label: 'VND', properties:{name:'Vietnamese đồng', flag:'vn'}, value: 'VND'},
  {label: 'VUV', properties:{name:'Vanuatu vatu', flag:'vu'}, value: 'VUV'},
  {label: 'WST', properties:{name:'Samoan tala', flag:'ws'}, value: 'WST'},
  {label: 'XAF', properties:{name:'CFA franc BEAC', flag:''}, value: 'XAF'},
  {label: 'XCD', properties:{name:'East Caribbean dollar', flag:''}, value: 'XCD'},
  {label: 'XCG', properties:{name:'Caribbean guilder', flag:''}, value: 'XCG'},
  {label: 'XOF', properties:{name:'CFA franc BCEAO', flag:''}, value: 'XOF'},
  {label: 'XPF', properties:{name:'CFP franc (franc Pacifique)', flag:''}, value: 'XPF'},
  {label: 'YER', properties:{name:'Yemeni rial', flag:'ye'}, value: 'YER'},
  {label: 'ZAR', properties:{name:'South African rand', flag:'za'}, value: 'ZAR'},
  {label: 'ZMW', properties:{name:'Zambian kwacha', flag:'zm'}, value: 'ZMW'},
  {label: 'ZWG', properties:{name:'Zimbabwe Gold', flag:'zw'}, value: 'ZWG'},
]