import {
  DATE_TIME_DEFINITION_DEFAULT,
  DATE_TIME_DEFINITION_FULL_DATE,
  DATE_TIME_DEFINITION_ISO_DATE,
  DATE_TIME_DEFINITION_ISO_DATE_TIME,
  DATE_TIME_DEFINITION_ISO_TIME,
  DATE_TIME_DEFINITION_LONG_DATE,
  DATE_TIME_DEFINITION_LONG_TIME,
  DATE_TIME_DEFINITION_MEDIUM_DATE,
  DATE_TIME_DEFINITION_MEDIUM_TIME,
  DATE_TIME_DEFINITION_PADDED_SHORT_DATE,
  DATE_TIME_DEFINITION_SHORT_DATE,
  DATE_TIME_DEFINITION_SHORT_TIME,
} from './types.js'

import type {
  DateTimeDefinitions,
} from './types.js'

export const dateTimeDefinitions: DateTimeDefinitions = {
  [DATE_TIME_DEFINITION_DEFAULT]: 'yyyy-mm-dd HH:MM:ss',
  [DATE_TIME_DEFINITION_FULL_DATE]: 'dddd, dd/mm/yyyy',
  [DATE_TIME_DEFINITION_ISO_DATE]: 'yyyy-mm-dd',
  [DATE_TIME_DEFINITION_ISO_DATE_TIME]: 'yyyy-mm-ddTHH:MM:ss',
  [DATE_TIME_DEFINITION_ISO_TIME]: 'HH:MM:ss',
  [DATE_TIME_DEFINITION_LONG_DATE]: 'yyyy mmmm d.',
  [DATE_TIME_DEFINITION_LONG_TIME]: 'hh:MM:ss TT Z',
  [DATE_TIME_DEFINITION_MEDIUM_DATE]: 'yyyy mmm. d.',
  [DATE_TIME_DEFINITION_MEDIUM_TIME]: 'h:MM:ss TT',
  [DATE_TIME_DEFINITION_PADDED_SHORT_DATE]: 'dd/mm/yyyy',
  [DATE_TIME_DEFINITION_SHORT_DATE]: 'd/m/yy',
  [DATE_TIME_DEFINITION_SHORT_TIME]: 'h:MM TT',
}