export const DAY_DOES_NOT_MATCH_CRITERIA = 'DAY_DOES_NOT_MATCH_CRITERIA'

export const EMPTY_DATE = 'EMPTY_DATE'

export const INVALID_DATE = 'INVALID_DATE'

export const INVALID_EMAIL = 'INVALID_EMAIL'

export const LIST_IS_EMPTY = 'LIST_IS_EMPTY'

export const MONTH_DOES_NOT_MATCH_CRITERIA = 'MONTH_DOES_NOT_MATCH_CRITERIA'

export const VALUE_BLOCKED = 'VALUE_BLOCKED'

export const VALUE_IS_NOT_BIG_ENOUGH = 'VALUE_IS_NOT_BIG_ENOUGH'

export const VALUE_IS_NOT_SMALL_ENOUGH = 'VALUE_IS_NOT_SMALL_ENOUGH'

export const VALUE_NOT_ALLOWED = 'VALUE_NOT_ALLOWED'

export const VALUE_REQUIRED = 'VALUE_REQUIRED'

export const VALUE_MATCHES_BLACKLISTED_COLUMN = 'VALUE_MATCHES_BLACKLISTED_COLUMN'

export const YEAR_DOES_NOT_MATCH_CRITERIA = 'YEAR_DOES_NOT_MATCH_CRITERIA'