export const COMPARISON_FAILED = 'COMPARISON_FAILED'

export const DATE_LENGTH_CAN_NOT_BE_COMPARED = 'DATE_LENGTH_CAN_NOT_BE_COMPARED'

export const DAY_DOES_NOT_MATCH_CRITERIA = 'DAY_DOES_NOT_MATCH_CRITERIA'

export const EMPTY_DATE = 'EMPTY_DATE'

export const INVALID_DATE = 'INVALID_DATE'

export const INVALID_EMAIL = 'INVALID_EMAIL'

export const LIST_IS_EMPTY = 'LIST_IS_EMPTY'

export const MONTH_DOES_NOT_MATCH_CRITERIA = 'MONTH_DOES_NOT_MATCH_CRITERIA'

export const VALUE_BLOCKED = 'VALUE_BLOCKED'

export const VALUE_DOES_NOT_HAVE_LOWERCASE = 'VALUE_DOES_NOT_HAVE_LOWERCASE'

export const VALUE_DOES_NOT_HAVE_UPPERCASE = 'VALUE_DOES_NOT_HAVE_UPPERCASE'

export const VALUE_DOES_NOT_MATCH_PATTERN = 'VALUE_DOES_NOT_MATCH_PATTERN'

export const VALUE_HAS_TO_MATCH_LENGTH = 'VALUE_HAS_TO_MATCH_LENGTH'

export const VALUE_IS_NOT_BIG_ENOUGH = 'VALUE_IS_NOT_BIG_ENOUGH'

export const VALUE_IS_NOT_BIG_ENOUGH_ALLOWING_EQUAL = 'VALUE_IS_NOT_BIG_ENOUGH_ALLOWING_EQUAL'

export const VALUE_IS_NOT_SMALL_ENOUGH = 'VALUE_IS_NOT_SMALL_ENOUGH'

export const VALUE_IS_NOT_SMALL_ENOUGH_ALLOWING_EQUAL = 'VALUE_IS_NOT_SMALL_ENOUGH_ALLOWING_EQUAL'

export const VALUE_IS_NOT_LONG_ENOUGH = 'VALUE_IS_NOT_LONG_ENOUGH'

export const VALUE_IS_NOT_LONG_ENOUGH_ALLOWING_EQUAL = 'VALUE_IS_NOT_LONG_ENOUGH_ALLOWING_EQUAL'

export const VALUE_IS_NOT_SHORT_ENOUGH = 'VALUE_IS_NOT_SHORT_ENOUGH'

export const VALUE_IS_NOT_SHORT_ENOUGH_ALLOWING_EQUAL = 'VALUE_IS_NOT_SHORT_ENOUGH_ALLOWING_EQUAL'

export const VALUE_MUST_HAVE_ONLY_LOWERCASE = 'VALUE_MUST_HAVE_ONLY_LOWERCASE'

export const VALUE_MUST_HAVE_ONLY_UPPERCASE = 'VALUE_MUST_HAVE_ONLY_UPPERCASE'

export const VALUE_NOT_ALLOWED = 'VALUE_NOT_ALLOWED'

export const VALUE_REQUIRED = 'VALUE_REQUIRED'

export const VALUE_MATCHES_BLACKLISTED_COLUMN = 'VALUE_MATCHES_BLACKLISTED_COLUMN'

export const YEAR_DOES_NOT_MATCH_CRITERIA = 'YEAR_DOES_NOT_MATCH_CRITERIA'