/**
 * Flags provded by Flag Icons https://github.com/lipis/flag-icons/tree/main
 */
export const countryOptions = [
  {label: 'Andorra', properties:{iso3: 'AND', country: true}, value: 'AD'},
  {label: 'United Arab Emirates', properties:{iso3: 'ARE', country: true}, value: 'AE'},
  {label: 'Afghanistan', properties:{iso3: 'AFG', country: true}, value: 'AF'},
  {label: 'Antigua and Barbuda', properties:{iso3: 'ATG', country: true}, value: 'AG'},
  {label: 'Anguilla', properties:{iso3: 'AIA', country: true}, value: 'AI'},
  {label: 'Albania', properties:{iso3: 'ALB', country: true}, value: 'AL'},
  {label: 'Armenia', properties:{iso3: 'ARM', country: true}, value: 'AM'},
  {label: 'Angola', properties:{iso3: 'AGO', country: true}, value: 'AO'},
  {label: 'Antarctica', properties:{iso3: 'ATA', country: true}, value: 'AQ'},
  {label: 'Argentina', properties:{iso3: 'ARG', country: true}, value: 'AR'},
  {label: 'American Samoa', properties:{iso3: 'ASM', country: true}, value: 'AS'},
  {label: 'Austria', properties:{iso3: 'AUT', country: true}, value: 'AT'},
  {label: 'Australia', properties:{iso3: 'AUS', country: true}, value: 'AU'},
  {label: 'Aruba', properties:{iso3: 'ABW', country: true}, value: 'AW'},
  {label: 'Åland Islands', properties:{iso3: 'ALA', country: true}, value: 'AX'},
  {label: 'Azerbaijan', properties:{iso3: 'AZE', country: true}, value: 'AZ'},
  {label: 'Bosnia and Herzegovina', properties:{iso3: 'BIH', country: true}, value: 'BA'},
  {label: 'Barbados', properties:{iso3: 'BRB', country: true}, value: 'BB'},
  {label: 'Bangladesh', properties:{iso3: 'BGD', country: true}, value: 'BD'},
  {label: 'Belgium', properties:{iso3: 'BEL', country: true}, value: 'BE'},
  {label: 'Burkina Faso', properties:{iso3: 'BFA', country: true}, value: 'BF'},
  {label: 'Bulgaria', properties:{iso3: 'BGR', country: true}, value: 'BG'},
  {label: 'Bahrain', properties:{iso3: 'BHR', country: true}, value: 'BH'},
  {label: 'Burundi', properties:{iso3: 'BDI', country: true}, value: 'BI'},
  {label: 'Benin', properties:{iso3: 'BEN', country: true}, value: 'BJ'},
  {label: 'Saint Barthélemy', properties:{iso3: 'BLM', country: true}, value: 'BL'},
  {label: 'Bermuda', properties:{iso3: 'BMU', country: true}, value: 'BM'},
  {label: 'Brunei Darussalam', properties:{iso3: 'BRN', country: true}, value: 'BN'},
  {label: 'Bolivia', properties:{iso3: 'BOL', country: true}, value: 'BO'},
  {label: 'Bonaire, Sint Eustatius and Saba', properties:{iso3: 'BES', country: true}, value: 'BQ'},
  {label: 'Brazil', properties:{iso3: 'BRA', country: true}, value: 'BR'},
  {label: 'Bahamas', properties:{iso3: 'BHS', country: true}, value: 'BS'},
  {label: 'Bhutan', properties:{iso3: 'BTN', country: true}, value: 'BT'},
  {label: 'Bouvet Island', properties:{iso3: 'BVT', country: true}, value: 'BV'},
  {label: 'Botswana', properties:{iso3: 'BWA', country: true}, value: 'BW'},
  {label: 'Belarus', properties:{iso3: 'BLR', country: true}, value: 'BY'},
  {label: 'Belize', properties:{iso3: 'BLZ', country: true}, value: 'BZ'},
  {label: 'Canada', properties:{iso3: 'CAN', country: true}, value: 'CA'},
  {label: 'Cocos (Keeling) Islands', properties:{iso3: 'CCK', country: true}, value: 'CC'},
  {label: 'Democratic Republic of the Congo', properties:{iso3: 'COD', country: true}, value: 'CD'},
  {label: 'Central African Republic', properties:{iso3: 'CAF', country: true}, value: 'CF'},
  {label: 'Congo', properties:{iso3: 'COG', country: true}, value: 'CG'},
  {label: 'Switzerland', properties:{iso3: 'CHE', country: true}, value: 'CH'},
  {label: 'Côte d\'Ivoire', properties:{iso3: 'CIV', country: true}, value: 'CI'},
  {label: 'Cook Islands', properties:{iso3: 'COK', country: true}, value: 'CK'},
  {label: 'Chile', properties:{iso3: 'CHL', country: true}, value: 'CL'},
  {label: 'Cameroon', properties:{iso3: 'CMR', country: true}, value: 'CM'},
  {label: 'China', properties:{iso3: 'CHN', country: true}, value: 'CN'},
  {label: 'Colombia', properties:{iso3: 'COL', country: true}, value: 'CO'},
  {label: 'Costa Rica', properties:{iso3: 'CRI', country: true}, value: 'CR'},
  {label: 'Cuba', properties:{iso3: 'CUB', country: true}, value: 'CU'},
  {label: 'Cabo Verde', properties:{iso3: 'CPV', country: true}, value: 'CV'},
  {label: 'Curaçao', properties:{iso3: 'CUW', country: true}, value: 'CW'},
  {label: 'Christmas Island', properties:{iso3: 'CXR', country: true}, value: 'CX'},
  {label: 'Cyprus', properties:{iso3: 'CYP', country: true}, value: 'CY'},
  {label: 'Czechia', properties:{iso3: 'CZE', country: true}, value: 'CZ'},
  {label: 'Germany', properties:{iso3: 'DEU', country: true}, value: 'DE'},
  {label: 'Djibouti', properties:{iso3: 'DJI', country: true}, value: 'DJ'},
  {label: 'Denmark', properties:{iso3: 'DNK', country: true}, value: 'DK'},
  {label: 'Dominica', properties:{iso3: 'DMA', country: true}, value: 'DM'},
  {label: 'Dominican Republic', properties:{iso3: 'DOM', country: true}, value: 'DO'},
  {label: 'Algeria', properties:{iso3: 'DZA', country: true}, value: 'DZ'},
  {label: 'Ecuador', properties:{iso3: 'ECU', country: true}, value: 'EC'},
  {label: 'Estonia', properties:{iso3: 'EST', country: true}, value: 'EE'},
  {label: 'Egypt', properties:{iso3: 'EGY', country: true}, value: 'EG'},
  {label: 'Western Sahara', properties:{iso3: 'ESH', country: true}, value: 'EH'},
  {label: 'Eritrea', properties:{iso3: 'ERI', country: true}, value: 'ER'},
  {label: 'Spain', properties:{iso3: 'ESP', country: true}, value: 'ES'},
  {label: 'Ethiopia', properties:{iso3: 'ETH', country: true}, value: 'ET'},
  {label: 'Finland', properties:{iso3: 'FIN', country: true}, value: 'FI'},
  {label: 'Fiji', properties:{iso3: 'FJI', country: true}, value: 'FJ'},
  {label: 'Falkland Islands', properties:{iso3: 'FLK', country: true}, value: 'FK'},
  {label: 'Micronesia', properties:{iso3: 'FSM', country: true}, value: 'FM'},
  {label: 'Faroe Islands', properties:{iso3: 'FRO', country: true}, value: 'FO'},
  {label: 'France', properties:{iso3: 'FRA', country: true}, value: 'FR'},
  {label: 'Gabon', properties:{iso3: 'GAB', country: true}, value: 'GA'},
  {label: 'United Kingdom', properties:{iso3: 'GBR', country: true}, value: 'GB'},
  {label: 'Grenada', properties:{iso3: 'GRD', country: true}, value: 'GD'},
  {label: 'Georgia', properties:{iso3: 'GEO', country: true}, value: 'GE'},
  {label: 'French Guiana', properties:{iso3: 'GUF', country: true}, value: 'GF'},
  {label: 'Guernsey', properties:{iso3: 'GGY', country: true}, value: 'GG'},
  {label: 'Ghana', properties:{iso3: 'GHA', country: true}, value: 'GH'},
  {label: 'Gibraltar', properties:{iso3: 'GIB', country: true}, value: 'GI'},
  {label: 'Greenland', properties:{iso3: 'GRL', country: true}, value: 'GL'},
  {label: 'Gambia', properties:{iso3: 'GMB', country: true}, value: 'GM'},
  {label: 'Guinea', properties:{iso3: 'GIN', country: true}, value: 'GN'},
  {label: 'Guadeloupe', properties:{iso3: 'GLP', country: true}, value: 'GP'},
  {label: 'Equatorial Guinea', properties:{iso3: 'GNQ', country: true}, value: 'GQ'},
  {label: 'Greece', properties:{iso3: 'GRC', country: true}, value: 'GR'},
  {label: 'South Georgia and the South Sandwich Islands', properties:{iso3: 'SGS', country: true}, value: 'GS'},
  {label: 'Guatemala', properties:{iso3: 'GTM', country: true}, value: 'GT'},
  {label: 'Guam', properties:{iso3: 'GUM', country: true}, value: 'GU'},
  {label: 'Guinea-Bissau', properties:{iso3: 'GNB', country: true}, value: 'GW'},
  {label: 'Guyana', properties:{iso3: 'GUY', country: true}, value: 'GY'},
  {label: 'Hong Kong', properties:{iso3: 'HKG', country: true}, value: 'HK'},
  {label: 'Heard Island and McDonald Islands', properties:{iso3: 'HMD', country: true}, value: 'HM'},
  {label: 'Honduras', properties:{iso3: 'HND', country: true}, value: 'HN'},
  {label: 'Croatia', properties:{iso3: 'HRV', country: true}, value: 'HR'},
  {label: 'Haiti', properties:{iso3: 'HTI', country: true}, value: 'HT'},
  {label: 'Hungary', properties:{iso3: 'HUN', country: true}, value: 'HU'},
  {label: 'Indonesia', properties:{iso3: 'IDN', country: true}, value: 'ID'},
  {label: 'Ireland', properties:{iso3: 'IRL', country: true}, value: 'IE'},
  {label: 'Israel', properties:{iso3: 'ISR', country: true}, value: 'IL'},
  {label: 'Isle of Man', properties:{iso3: 'IMN', country: true}, value: 'IM'},
  {label: 'India', properties:{iso3: 'IND', country: true}, value: 'IN'},
  {label: 'British Indian Ocean Territory', properties:{iso3: 'IOT', country: true}, value: 'IO'},
  {label: 'Iraq', properties:{iso3: 'IRQ', country: true}, value: 'IQ'},
  {label: 'Iran', properties:{iso3: 'IRN', country: true}, value: 'IR'},
  {label: 'Iceland', properties:{iso3: 'ISL', country: true}, value: 'IS'},
  {label: 'Italy', properties:{iso3: 'ITA', country: true}, value: 'IT'},
  {label: 'Jersey', properties:{iso3: 'JEY', country: true}, value: 'JE'},
  {label: 'Jamaica', properties:{iso3: 'JAM', country: true}, value: 'JM'},
  {label: 'Jordan', properties:{iso3: 'JOR', country: true}, value: 'JO'},
  {label: 'Japan', properties:{iso3: 'JPN', country: true}, value: 'JP'},
  {label: 'Kenya', properties:{iso3: 'KEN', country: true}, value: 'KE'},
  {label: 'Kyrgyzstan', properties:{iso3: 'KGZ', country: true}, value: 'KG'},
  {label: 'Cambodia', properties:{iso3: 'KHM', country: true}, value: 'KH'},
  {label: 'Kiribati', properties:{iso3: 'KIR', country: true}, value: 'KI'},
  {label: 'Comoros', properties:{iso3: 'COM', country: true}, value: 'KM'},
  {label: 'Saint Kitts and Nevis', properties:{iso3: 'KNA', country: true}, value: 'KN'},
  {label: 'Democratic People\'s Republic of Korea', properties:{iso3: 'PRK', country: true}, value: 'KP'},
  {label: 'South Korea', properties:{iso3: 'KOR', country: true}, value: 'KR'},
  {label: 'Kuwait', properties:{iso3: 'KWT', country: true}, value: 'KW'},
  {label: 'Cayman Islands', properties:{iso3: 'CYM', country: true}, value: 'KY'},
  {label: 'Kazakhstan', properties:{iso3: 'KAZ', country: true}, value: 'KZ'},
  {label: 'Laos', properties:{iso3: 'LAO', country: true}, value: 'LA'},
  {label: 'Lebanon', properties:{iso3: 'LBN', country: true}, value: 'LB'},
  {label: 'Saint Lucia', properties:{iso3: 'LCA', country: true}, value: 'LC'},
  {label: 'Liechtenstein', properties:{iso3: 'LIE', country: true}, value: 'LI'},
  {label: 'Sri Lanka', properties:{iso3: 'LKA', country: true}, value: 'LK'},
  {label: 'Liberia', properties:{iso3: 'LBR', country: true}, value: 'LR'},
  {label: 'Lesotho', properties:{iso3: 'LSO', country: true}, value: 'LS'},
  {label: 'Lithuania', properties:{iso3: 'LTU', country: true}, value: 'LT'},
  {label: 'Luxembourg', properties:{iso3: 'LUX', country: true}, value: 'LU'},
  {label: 'Latvia', properties:{iso3: 'LVA', country: true}, value: 'LV'},
  {label: 'Libya', properties:{iso3: 'LBY', country: true}, value: 'LY'},
  {label: 'Morocco', properties:{iso3: 'MAR', country: true}, value: 'MA'},
  {label: 'Monaco', properties:{iso3: 'MCO', country: true}, value: 'MC'},
  {label: 'Moldova', properties:{iso3: 'MDA', country: true}, value: 'MD'},
  {label: 'Montenegro', properties:{iso3: 'MNE', country: true}, value: 'ME'},
  {label: 'Saint Martin', properties:{iso3: 'MAF', country: true}, value: 'MF'},
  {label: 'Madagascar', properties:{iso3: 'MDG', country: true}, value: 'MG'},
  {label: 'Marshall Islands', properties:{iso3: 'MHL', country: true}, value: 'MH'},
  {label: 'North Macedonia', properties:{iso3: 'MKD', country: true}, value: 'MK'},
  {label: 'Mali', properties:{iso3: 'MLI', country: true}, value: 'ML'},
  {label: 'Myanmar', properties:{iso3: 'MMR', country: true}, value: 'MM'},
  {label: 'Mongolia', properties:{iso3: 'MNG', country: true}, value: 'MN'},
  {label: 'Macao', properties:{iso3: 'MAC', country: true}, value: 'MO'},
  {label: 'Northern Mariana Islands', properties:{iso3: 'MNP', country: true}, value: 'MP'},
  {label: 'Martinique', properties:{iso3: 'MTQ', country: true}, value: 'MQ'},
  {label: 'Mauritania', properties:{iso3: 'MRT', country: true}, value: 'MR'},
  {label: 'Montserrat', properties:{iso3: 'MSR', country: true}, value: 'MS'},
  {label: 'Malta', properties:{iso3: 'MLT', country: true}, value: 'MT'},
  {label: 'Mauritius', properties:{iso3: 'MUS', country: true}, value: 'MU'},
  {label: 'Maldives', properties:{iso3: 'MDV', country: true}, value: 'MV'},
  {label: 'Malawi', properties:{iso3: 'MWI', country: true}, value: 'MW'},
  {label: 'Mexico', properties:{iso3: 'MEX', country: true}, value: 'MX'},
  {label: 'Malaysia', properties:{iso3: 'MYS', country: true}, value: 'MY'},
  {label: 'Mozambique', properties:{iso3: 'MOZ', country: true}, value: 'MZ'},
  {label: 'Namibia', properties:{iso3: 'NAM', country: true}, value: 'NA'},
  {label: 'New Caledonia', properties:{iso3: 'NCL', country: true}, value: 'NC'},
  {label: 'Niger', properties:{iso3: 'NER', country: true}, value: 'NE'},
  {label: 'Norfolk Island', properties:{iso3: 'NFK', country: true}, value: 'NF'},
  {label: 'Nigeria', properties:{iso3: 'NGA', country: true}, value: 'NG'},
  {label: 'Nicaragua', properties:{iso3: 'NIC', country: true}, value: 'NI'},
  {label: 'Netherlands', properties:{iso3: 'NLD', country: true}, value: 'NL'},
  {label: 'Norway', properties:{iso3: 'NOR', country: true}, value: 'NO'},
  {label: 'Nepal', properties:{iso3: 'NPL', country: true}, value: 'NP'},
  {label: 'Nauru', properties:{iso3: 'NRU', country: true}, value: 'NR'},
  {label: 'Niue', properties:{iso3: 'NIU', country: true}, value: 'NU'},
  {label: 'New Zealand', properties:{iso3: 'NZL', country: true}, value: 'NZ'},
  {label: 'Oman', properties:{iso3: 'OMN', country: true}, value: 'OM'},
  {label: 'Panama', properties:{iso3: 'PAN', country: true}, value: 'PA'},
  {label: 'Peru', properties:{iso3: 'PER', country: true}, value: 'PE'},
  {label: 'French Polynesia', properties:{iso3: 'PYF', country: true}, value: 'PF'},
  {label: 'Papua New Guinea', properties:{iso3: 'PNG', country: true}, value: 'PG'},
  {label: 'Philippines', properties:{iso3: 'PHL', country: true}, value: 'PH'},
  {label: 'Pakistan', properties:{iso3: 'PAK', country: true}, value: 'PK'},
  {label: 'Poland', properties:{iso3: 'POL', country: true}, value: 'PL'},
  {label: 'Saint Pierre and Miquelon', properties:{iso3: 'SPM', country: true}, value: 'PM'},
  {label: 'Pitcairn', properties:{iso3: 'PCN', country: true}, value: 'PN'},
  {label: 'Puerto Rico', properties:{iso3: 'PRI', country: true}, value: 'PR'},
  {label: 'Palestine', properties:{iso3: 'PSE', country: true}, value: 'PS'},
  {label: 'Portugal', properties:{iso3: 'PRT', country: true}, value: 'PT'},
  {label: 'Palau', properties:{iso3: 'PLW', country: true}, value: 'PW'},
  {label: 'Paraguay', properties:{iso3: 'PRY', country: true}, value: 'PY'},
  {label: 'Qatar', properties:{iso3: 'QAT', country: true}, value: 'QA'},
  {label: 'Réunion', properties:{iso3: 'REU', country: true}, value: 'RE'},
  {label: 'Romania', properties:{iso3: 'ROU', country: true}, value: 'RO'},
  {label: 'Serbia', properties:{iso3: 'SRB', country: true}, value: 'RS'},
  {label: 'Russian Federation', properties:{iso3: 'RUS', country: true}, value: 'RU'},
  {label: 'Rwanda', properties:{iso3: 'RWA', country: true}, value: 'RW'},
  {label: 'Saudi Arabia', properties:{iso3: 'SAU', country: true}, value: 'SA'},
  {label: 'Solomon Islands', properties:{iso3: 'SLB', country: true}, value: 'SB'},
  {label: 'Seychelles', properties:{iso3: 'SYC', country: true}, value: 'SC'},
  {label: 'Sudan', properties:{iso3: 'SDN', country: true}, value: 'SD'},
  {label: 'Sweden', properties:{iso3: 'SWE', country: true}, value: 'SE'},
  {label: 'Singapore', properties:{iso3: 'SGP', country: true}, value: 'SG'},
  {label: 'Saint Helena, Ascension and Tristan da Cunha', properties:{iso3: 'SHN', country: true}, value: 'SH'},
  {label: 'Slovenia', properties:{iso3: 'SVN', country: true}, value: 'SI'},
  {label: 'Svalbard and Jan Mayen', properties:{iso3: 'SJM', country: true}, value: 'SJ'},
  {label: 'Slovakia', properties:{iso3: 'SVK', country: true}, value: 'SK'},
  {label: 'Sierra Leone', properties:{iso3: 'SLE', country: true}, value: 'SL'},
  {label: 'San Marino', properties:{iso3: 'SMR', country: true}, value: 'SM'},
  {label: 'Senegal', properties:{iso3: 'SEN', country: true}, value: 'SN'},
  {label: 'Somalia', properties:{iso3: 'SOM', country: true}, value: 'SO'},
  {label: 'Suriname', properties:{iso3: 'SUR', country: true}, value: 'SR'},
  {label: 'South Sudan', properties:{iso3: 'SSD', country: true}, value: 'SS'},
  {label: 'Sao Tome and Principe', properties:{iso3: 'STP', country: true}, value: 'ST'},
  {label: 'El Salvador', properties:{iso3: 'SLV', country: true}, value: 'SV'},
  {label: 'Sint Maarten', properties:{iso3: 'SXM', country: true}, value: 'SX'},
  {label: 'Syrian Arab Republic', properties:{iso3: 'SYR', country: true}, value: 'SY'},
  {label: 'Eswatini', properties:{iso3: 'SWZ', country: true}, value: 'SZ'},
  {label: 'Turks and Caicos Islands', properties:{iso3: 'TCA', country: true}, value: 'TC'},
  {label: 'Chad', properties:{iso3: 'TCD', country: true}, value: 'TD'},
  {label: 'French Southern Territories', properties:{iso3: 'ATF', country: true}, value: 'TF'},
  {label: 'Togo', properties:{iso3: 'TGO', country: true}, value: 'TG'},
  {label: 'Thailand', properties:{iso3: 'THA', country: true}, value: 'TH'},
  {label: 'Tajikistan', properties:{iso3: 'TJK', country: true}, value: 'TJ'},
  {label: 'Tokelau', properties:{iso3: 'TKL', country: true}, value: 'TK'},
  {label: 'Timor-Leste', properties:{iso3: 'TLS', country: true}, value: 'TL'},
  {label: 'Turkmenistan', properties:{iso3: 'TKM', country: true}, value: 'TM'},
  {label: 'Tunisia', properties:{iso3: 'TUN', country: true}, value: 'TN'},
  {label: 'Tonga', properties:{iso3: 'TON', country: true}, value: 'TO'},
  {label: 'Turkey', properties:{iso3: 'TUR', country: true}, value: 'TR'},
  {label: 'Trinidad and Tobago', properties:{iso3: 'TTO', country: true}, value: 'TT'},
  {label: 'Tuvalu', properties:{iso3: 'TUV', country: true}, value: 'TV'},
  {label: 'Taiwan', properties:{iso3: 'TWN', country: true}, value: 'TW'},
  {label: 'Tanzania', properties:{iso3: 'TZA', country: true}, value: 'TZ'},
  {label: 'Ukraine', properties:{iso3: 'UKR', country: true}, value: 'UA'},
  {label: 'Uganda', properties:{iso3: 'UGA', country: true}, value: 'UG'},
  {label: 'United States Minor Outlying Islands', properties:{iso3: 'UMI', country: true}, value: 'UM'},
  {label: 'United States of America', properties:{iso3: 'USA', country: true}, value: 'US'},
  {label: 'Uruguay', properties:{iso3: 'URY', country: true}, value: 'UY'},
  {label: 'Uzbekistan', properties:{iso3: 'UZB', country: true}, value: 'UZ'},
  {label: 'Holy See', properties:{iso3: 'VAT', country: true}, value: 'VA'},
  {label: 'Saint Vincent and the Grenadines', properties:{iso3: 'VCT', country: true}, value: 'VC'},
  {label: 'Venezuela', properties:{iso3: 'VEN', country: true}, value: 'VE'},
  {label: 'British Virgin Islands', properties:{iso3: 'VGB', country: true}, value: 'VG'},
  {label: 'Virgin Islands', properties:{iso3: 'VIR', country: true}, value: 'VI'},
  {label: 'Viet Nam', properties:{iso3: 'VNM', country: true}, value: 'VN'},
  {label: 'Vanuatu', properties:{iso3: 'VUT', country: true}, value: 'VU'},
  {label: 'Wallis and Futuna', properties:{iso3: 'WLF', country: true}, value: 'WF'},
  {label: 'Samoa', properties:{iso3: 'WSM', country: true}, value: 'WS'},
  {label: 'Yemen', properties:{iso3: 'YEM', country: true}, value: 'YE'},
  {label: 'Mayotte', properties:{iso3: 'MYT', country: true}, value: 'YT'},
  {label: 'South Africa', properties:{iso3: 'ZAF', country: true}, value: 'ZA'},
  {label: 'Zambia', properties:{iso3: 'ZMB', country: true}, value: 'ZM'},
  {label: 'Zimbabwe', properties:{iso3: 'ZWE', country: true}, value: 'ZW'},
  {label: 'League of Arab States', properties:{iso3: '', country: false}, value: 'ARAB'},
  {label: 'Association of Southeast Asian Nations', properties:{iso3: '', country: false}, value: 'ASEAN'},
  {label: 'Central European Free Trade Agreement', properties:{iso3: '', country: false}, value: 'CEFTA'},
  {label: 'Clipperton Island', properties:{iso3: '', country: false}, value: 'CP'},
  {label: 'Diego Garcia', properties:{iso3: '', country: false}, value: 'DG'},
  {label: 'East African Community', properties:{iso3: '', country: false}, value: 'EAC'},
  {label: 'Catalonia', properties:{iso3: '', country: false}, value: 'ES-CT'},
  {label: 'Galicia', properties:{iso3: '', country: false}, value: 'ES-GA'},
  {label: 'Basque Country', properties:{iso3: '', country: false}, value: 'ES-PV'},
  {label: 'European Union', properties:{iso3: '', country: false}, value: 'EU'},
  {label: 'England', properties:{iso3: '', country: false}, value: 'GB-ENG'},
  {label: 'Northern Ireland', properties:{iso3: '', country: false}, value: 'GB-NIR'},
  {label: 'Scotland', properties:{iso3: '', country: false}, value: 'GB-SCT'},
  {label: 'Wales', properties:{iso3: '', country: false}, value: 'GB-WLS'},
  {label: 'Canary Islands', properties:{iso3: '', country: false}, value: 'IC'},
  {label: 'Pacific Community', properties:{iso3: '', country: false}, value: 'PC'},
  {label: 'Ascension Island', properties:{iso3: '', country: false}, value: 'SH-AC'},
  {label: 'Saint Helena', properties:{iso3: '', country: false}, value: 'SH-HL'},
  {label: 'Tristan de Cunha', properties:{iso3: '', country: false}, value: 'SH-TA'},
  {label: 'United Nations', properties:{iso3: '', country: false}, value: 'UN'},
  {label: 'Kosovo', properties:{iso3: '', country: false}, value: 'XK'},
]