/**
 * Flags provded by Flag Icons https://github.com/lipis/flag-icons/tree/main
 */
export const phonePrefixOptions = [
  {label: 'Canada', properties:{iso2: 'CA'}, value: '+1'},
  {label: 'United States of America', properties:{iso2: 'US'}, value: '+1'},
  {label: 'Bahamas', properties:{iso2: 'BS'}, value: '+1-242'},
  {label: 'Barbados', properties:{iso2: 'BB'}, value: '+1-246'},
  {label: 'Anguilla', properties:{iso2: 'AI'}, value: '+1-264'},
  {label: 'Antigua and Barbuda', properties:{iso2: 'AG'}, value: '+1-268'},
  {label: 'British Virgin Islands', properties:{iso2: 'VG'}, value: '+1-284'},
  {label: 'Virgin Islands', properties:{iso2: 'VI'}, value: '+1-340'},
  {label: 'Cayman Islands', properties:{iso2: 'KY'}, value: '+1-345'},
  {label: 'Bermuda', properties:{iso2: 'BM'}, value: '+1-441'},
  {label: 'Grenada', properties:{iso2: 'GD'}, value: '+1-473'},
  {label: 'Turks and Caicos Islands', properties:{iso2: 'TC'}, value: '+1-649'},
  {label: 'Jamaica', properties:{iso2: 'JM'}, value: '+1-876'},
  {label: 'Jamaica', properties:{iso2: 'JM'}, value: '+1-658'},
  {label: 'Montserrat', properties:{iso2: 'MS'}, value: '+1-664'},
  {label: 'Northern Mariana Islands', properties:{iso2: 'MP'}, value: '+1-670'},
  {label: 'Guam', properties:{iso2: 'GU'}, value: '+1-671'},
  {label: 'American Samoa', properties:{iso2: 'AS'}, value: '+1-684'},
  {label: 'Sint Maarten', properties:{iso2: 'SX'}, value: '+1-721'},
  {label: 'Saint Lucia', properties:{iso2: 'LC'}, value: '+1-758'},
  {label: 'Dominica', properties:{iso2: 'DM'}, value: '+1-767'},
  {label: 'Saint Vincent and the Grenadines', properties:{iso2: 'VC'}, value: '+1-784'},
  {label: 'Puerto Rico', properties:{iso2: 'PR'}, value: '+1-939'},
  {label: 'Puerto Rico', properties:{iso2: 'PR'}, value: '+1-787'},
  {label: 'Dominican Republic', properties:{iso2: 'DO'}, value: '+1-849'},
  {label: 'Dominican Republic', properties:{iso2: 'DO'}, value: '+1-829'},
  {label: 'Dominican Republic', properties:{iso2: 'DO'}, value: '+1-809'},
  {label: 'Trinidad and Tobago', properties:{iso2: 'TT'}, value: '+1-868'},
  {label: 'Saint Kitts and Nevis', properties:{iso2: 'KN'}, value: '+1-869'},
  {label: 'Egypt', properties:{iso2: 'EG'}, value: '+20'},
  {label: 'South Africa', properties:{iso2: 'ZA'}, value: '+27'},
  {label: 'Greece', properties:{iso2: 'GR'}, value: '+30'},
  {label: 'Netherlands', properties:{iso2: 'NL'}, value: '+31'},
  {label: 'Belgium', properties:{iso2: 'BE'}, value: '+32'},
  {label: 'France', properties:{iso2: 'FR'}, value: '+33'},
  {label: 'Spain', properties:{iso2: 'ES'}, value: '+34'},
  {label: 'Hungary', properties:{iso2: 'HU'}, value: '+36'},
  {label: 'Italy', properties:{iso2: 'IT'}, value: '+39'},
  {label: 'Romania', properties:{iso2: 'RO'}, value: '+40'},
  {label: 'Switzerland', properties:{iso2: 'CH'}, value: '+41'},
  {label: 'Austria', properties:{iso2: 'AT'}, value: '+43'},
  {label: 'United Kingdom', properties:{iso2: 'GB'}, value: '+44'},
  {label: 'Denmark', properties:{iso2: 'DK'}, value: '+45'},
  {label: 'Sweden', properties:{iso2: 'SE'}, value: '+46'},
  {label: 'Norway', properties:{iso2: 'NO'}, value: '+47'},
  {label: 'Poland', properties:{iso2: 'PL'}, value: '+48'},
  {label: 'Germany', properties:{iso2: 'DE'}, value: '+49'},
  {label: 'Peru', properties:{iso2: 'PE'}, value: '+51'},
  {label: 'Mexico', properties:{iso2: 'MX'}, value: '+52'},
  {label: 'Cuba', properties:{iso2: 'CU'}, value: '+53'},
  {label: 'Argentina', properties:{iso2: 'AR'}, value: '+54'},
  {label: 'Brazil', properties:{iso2: 'BR'}, value: '+55'},
  {label: 'Chile', properties:{iso2: 'CL'}, value: '+56'},
  {label: 'Colombia', properties:{iso2: 'CO'}, value: '+57'},
  {label: 'Venezuela', properties:{iso2: 'VE'}, value: '+58'},
  {label: 'Malaysia', properties:{iso2: 'MY'}, value: '+60'},
  {label: 'Australia', properties:{iso2: 'AU'}, value: '+61'},
  {label: 'Indonesia', properties:{iso2: 'ID'}, value: '+62'},
  {label: 'Philippines', properties:{iso2: 'PH'}, value: '+63'},
  {label: 'New Zealand', properties:{iso2: 'NZ'}, value: '+64'},
  {label: 'Singapore', properties:{iso2: 'SG'}, value: '+65'},
  {label: 'Thailand', properties:{iso2: 'TH'}, value: '+66'},
  {label: 'South Korea', properties:{iso2: 'KR'}, value: '+82'},
  {label: 'Afghanistan', properties:{iso2: 'AF'}, value: '+93'},
  {label: 'Myanmar', properties:{iso2: 'MM'}, value: '+95'},
  {label: 'Morocco', properties:{iso2: 'MA'}, value: '+212'},
  {label: 'Mali', properties:{iso2: 'ML'}, value: '+223'},
  {label: 'Côte d\'Ivoire', properties:{iso2: 'CI'}, value: '+225'},
  {label: 'Burkina Faso', properties:{iso2: 'BF'}, value: '+226'},
  {label: 'Niger', properties:{iso2: 'NE'}, value: '+227'},
  {label: 'Ghana', properties:{iso2: 'GH'}, value: '+233'},
  {label: 'Democratic Republic of the Congo', properties:{iso2: 'CD'}, value: '+243'},
  {label: 'Tanzania', properties:{iso2: 'TZ'}, value: '+255'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+79'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+78'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+75'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+74'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+73'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+72'},
  {label: 'Russian Federation', properties:{iso2: 'RU'}, value: '+71'},
  {label: 'Japan', properties:{iso2: 'JP'}, value: '+81'},
  {label: 'Viet Nam', properties:{iso2: 'VN'}, value: '+84'},
  {label: 'China', properties:{iso2: 'CN'}, value: '+86'},
  {label: 'Turkey', properties:{iso2: 'TR'}, value: '+90'},
  {label: 'India', properties:{iso2: 'IN'}, value: '+91'},
  {label: 'Pakistan', properties:{iso2: 'PK'}, value: '+92'},
  {label: 'Sri Lanka', properties:{iso2: 'LK'}, value: '+94'},
  {label: 'Iran', properties:{iso2: 'IR'}, value: '+98'},
  {label: 'South Sudan', properties:{iso2: 'SS'}, value: '+211'},
  {label: 'Western Sahara', properties:{iso2: 'EH'}, value: '+212'},
  {label: 'Algeria', properties:{iso2: 'DZ'}, value: '+213'},
  {label: 'Tunisia', properties:{iso2: 'TN'}, value: '+216'},
  {label: 'Libya', properties:{iso2: 'LY'}, value: '+218'},
  {label: 'Gambia', properties:{iso2: 'GM'}, value: '+220'},
  {label: 'Senegal', properties:{iso2: 'SN'}, value: '+221'},
  {label: 'Mauritania', properties:{iso2: 'MR'}, value: '+222'},
  {label: 'Guinea', properties:{iso2: 'GN'}, value: '+224'},
  {label: 'Togo', properties:{iso2: 'TG'}, value: '+228'},
  {label: 'Benin', properties:{iso2: 'BJ'}, value: '+229'},
  {label: 'Mauritius', properties:{iso2: 'MU'}, value: '+230'},
  {label: 'Liberia', properties:{iso2: 'LR'}, value: '+231'},
  {label: 'Sierra Leone', properties:{iso2: 'SL'}, value: '+232'},
  {label: 'Nigeria', properties:{iso2: 'NG'}, value: '+234'},
  {label: 'Chad', properties:{iso2: 'TD'}, value: '+235'},
  {label: 'Central African Republic', properties:{iso2: 'CF'}, value: '+236'},
  {label: 'Cameroon', properties:{iso2: 'CM'}, value: '+237'},
  {label: 'Cabo Verde', properties:{iso2: 'CV'}, value: '+238'},
  {label: 'Sao Tome and Principe', properties:{iso2: 'ST'}, value: '+239'},
  {label: 'Equatorial Guinea', properties:{iso2: 'GQ'}, value: '+240'},
  {label: 'Gabon', properties:{iso2: 'GA'}, value: '+241'},
  {label: 'Congo', properties:{iso2: 'CG'}, value: '+242'},
  {label: 'Angola', properties:{iso2: 'AO'}, value: '+244'},
  {label: 'Guinea-Bissau', properties:{iso2: 'GW'}, value: '+245'},
  {label: 'Seychelles', properties:{iso2: 'SC'}, value: '+248'},
  {label: 'Sudan', properties:{iso2: 'SD'}, value: '+249'},
  {label: 'Rwanda', properties:{iso2: 'RW'}, value: '+250'},
  {label: 'Ethiopia', properties:{iso2: 'ET'}, value: '+251'},
  {label: 'Somalia', properties:{iso2: 'SO'}, value: '+252'},
  {label: 'Djibouti', properties:{iso2: 'DJ'}, value: '+253'},
  {label: 'Kenya', properties:{iso2: 'KE'}, value: '+254'},
  {label: 'Uganda', properties:{iso2: 'UG'}, value: '+256'},
  {label: 'Burundi', properties:{iso2: 'BI'}, value: '+257'},
  {label: 'Mozambique', properties:{iso2: 'MZ'}, value: '+258'},
  {label: 'Zambia', properties:{iso2: 'ZM'}, value: '+260'},
  {label: 'Madagascar', properties:{iso2: 'MG'}, value: '+261'},
  {label: 'Réunion', properties:{iso2: 'RE'}, value: '+262'},
  {label: 'Mayotte', properties:{iso2: 'YT'}, value: '+639'},
  {label: 'Mayotte', properties:{iso2: 'YT'}, value: '+262'},
  {label: 'Zimbabwe', properties:{iso2: 'ZW'}, value: '+263'},
  {label: 'Namibia', properties:{iso2: 'NA'}, value: '+264'},
  {label: 'Malawi', properties:{iso2: 'MW'}, value: '+265'},
  {label: 'Lesotho', properties:{iso2: 'LS'}, value: '+266'},
  {label: 'Botswana', properties:{iso2: 'BW'}, value: '+267'},
  {label: 'Eswatini', properties:{iso2: 'SZ'}, value: '+268'},
  {label: 'Comoros', properties:{iso2: 'KM'}, value: '+269'},
  {label: 'Eritrea', properties:{iso2: 'ER'}, value: '+291'},
  {label: 'Aruba', properties:{iso2: 'AW'}, value: '+297'},
  {label: 'Faroe Islands', properties:{iso2: 'FO'}, value: '+298'},
  {label: 'Greenland', properties:{iso2: 'GL'}, value: '+299'},
  {label: 'Gibraltar', properties:{iso2: 'GI'}, value: '+350'},
  {label: 'Portugal', properties:{iso2: 'PT'}, value: '+351'},
  {label: 'Luxembourg', properties:{iso2: 'LU'}, value: '+352'},
  {label: 'Ireland', properties:{iso2: 'IE'}, value: '+353'},
  {label: 'Iceland', properties:{iso2: 'IS'}, value: '+354'},
  {label: 'Albania', properties:{iso2: 'AL'}, value: '+355'},
  {label: 'Malta', properties:{iso2: 'MT'}, value: '+356'},
  {label: 'Cyprus', properties:{iso2: 'CY'}, value: '+357'},
  {label: 'Finland', properties:{iso2: 'FI'}, value: '+358'},
  {label: 'Bulgaria', properties:{iso2: 'BG'}, value: '+359'},
  {label: 'Lithuania', properties:{iso2: 'LT'}, value: '+370'},
  {label: 'Latvia', properties:{iso2: 'LV'}, value: '+371'},
  {label: 'Estonia', properties:{iso2: 'EE'}, value: '+372'},
  {label: 'Moldova', properties:{iso2: 'MD'}, value: '+373'},
  {label: 'Armenia', properties:{iso2: 'AM'}, value: '+374'},
  {label: 'Belarus', properties:{iso2: 'BY'}, value: '+375'},
  {label: 'Andorra', properties:{iso2: 'AD'}, value: '+376'},
  {label: 'Monaco', properties:{iso2: 'MC'}, value: '+377'},
  {label: 'San Marino', properties:{iso2: 'SM'}, value: '+378'},
  {label: 'Holy See', properties:{iso2: 'VA'}, value: '+39-06-698'},
  {label: 'Ukraine', properties:{iso2: 'UA'}, value: '+380'},
  {label: 'Serbia', properties:{iso2: 'RS'}, value: '+381'},
  {label: 'Montenegro', properties:{iso2: 'ME'}, value: '+382'},
  {label: 'Croatia', properties:{iso2: 'HR'}, value: '+385'},
  {label: 'Slovenia', properties:{iso2: 'SI'}, value: '+386'},
  {label: 'Bosnia and Herzegovina', properties:{iso2: 'BA'}, value: '+387'},
  {label: 'North Macedonia', properties:{iso2: 'MK'}, value: '+389'},
  {label: 'Czechia', properties:{iso2: 'CZ'}, value: '+420'},
  {label: 'Slovakia', properties:{iso2: 'SK'}, value: '+421'},
  {label: 'Liechtenstein', properties:{iso2: 'LI'}, value: '+423'},
  {label: 'Guernsey', properties:{iso2: 'GG'}, value: '+44-1481'},
  {label: 'Jersey', properties:{iso2: 'JE'}, value: '+44-1534'},
  {label: 'Isle of Man', properties:{iso2: 'IM'}, value: '+44-1624'},
  {label: 'Falkland Islands', properties:{iso2: 'FK'}, value: '+500'},
  {label: 'Belize', properties:{iso2: 'BZ'}, value: '+501'},
  {label: 'Guatemala', properties:{iso2: 'GT'}, value: '+502'},
  {label: 'El Salvador', properties:{iso2: 'SV'}, value: '+503'},
  {label: 'Honduras', properties:{iso2: 'HN'}, value: '+504'},
  {label: 'Nicaragua', properties:{iso2: 'NI'}, value: '+505'},
  {label: 'Costa Rica', properties:{iso2: 'CR'}, value: '+506'},
  {label: 'Panama', properties:{iso2: 'PA'}, value: '+507'},
  {label: 'Saint Pierre and Miquelon', properties:{iso2: 'PM'}, value: '+508'},
  {label: 'Haiti', properties:{iso2: 'HT'}, value: '+509'},
  {label: 'Saint Barthélemy', properties:{iso2: 'BL'}, value: '+590'},
  {label: 'Saint Martin', properties:{iso2: 'MF'}, value: '+590'},
  {label: 'Guadeloupe', properties:{iso2: 'GP'}, value: '+590'},
  {label: 'Bolivia', properties:{iso2: 'BO'}, value: '+591'},
  {label: 'Guyana', properties:{iso2: 'GY'}, value: '+592'},
  {label: 'Ecuador', properties:{iso2: 'EC'}, value: '+593'},
  {label: 'French Guiana', properties:{iso2: 'GF'}, value: '+594'},
  {label: 'Paraguay', properties:{iso2: 'PY'}, value: '+595'},
  {label: 'Martinique', properties:{iso2: 'MQ'}, value: '+596'},
  {label: 'Suriname', properties:{iso2: 'SR'}, value: '+597'},
  {label: 'Uruguay', properties:{iso2: 'UY'}, value: '+598'},
  {label: 'Curaçao', properties:{iso2: 'CW'}, value: '+599-9'},
  {label: 'Timor-Leste', properties:{iso2: 'TL'}, value: '+670'},
  {label: 'Brunei Darussalam', properties:{iso2: 'BN'}, value: '+673'},
  {label: 'Nauru', properties:{iso2: 'NR'}, value: '+674'},
  {label: 'Papua New Guinea', properties:{iso2: 'PG'}, value: '+675'},
  {label: 'Tonga', properties:{iso2: 'TO'}, value: '+676'},
  {label: 'Solomon Islands', properties:{iso2: 'SB'}, value: '+677'},
  {label: 'Vanuatu', properties:{iso2: 'VU'}, value: '+678'},
  {label: 'Fiji', properties:{iso2: 'FJ'}, value: '+679'},
  {label: 'Palau', properties:{iso2: 'PW'}, value: '+680'},
  {label: 'Wallis and Futuna', properties:{iso2: 'WF'}, value: '+681'},
  {label: 'Cook Islands', properties:{iso2: 'CK'}, value: '+682'},
  {label: 'Niue', properties:{iso2: 'NU'}, value: '+683'},
  {label: 'Samoa', properties:{iso2: 'WS'}, value: '+685'},
  {label: 'Kiribati', properties:{iso2: 'KI'}, value: '+686'},
  {label: 'New Caledonia', properties:{iso2: 'NC'}, value: '+687'},
  {label: 'Tuvalu', properties:{iso2: 'TV'}, value: '+688'},
  {label: 'French Polynesia', properties:{iso2: 'PF'}, value: '+689'},
  {label: 'Tokelau', properties:{iso2: 'TK'}, value: '+690'},
  {label: 'Micronesia', properties:{iso2: 'FM'}, value: '+691'},
  {label: 'Marshall Islands', properties:{iso2: 'MH'}, value: '+692'},
  {label: 'Kazakhstan', properties:{iso2: 'KZ'}, value: '+77'},
  {label: 'Kazakhstan', properties:{iso2: 'KZ'}, value: '+76'},
  {label: 'Democratic People\'s Republic of Korea', properties:{iso2: 'KP'}, value: '+850'},
  {label: 'Hong Kong', properties:{iso2: 'HK'}, value: '+852'},
  {label: 'Macao', properties:{iso2: 'MO'}, value: '+853'},
  {label: 'Cambodia', properties:{iso2: 'KH'}, value: '+855'},
  {label: 'Laos', properties:{iso2: 'LA'}, value: '+856'},
  {label: 'Bangladesh', properties:{iso2: 'BD'}, value: '+880'},
  {label: 'Taiwan', properties:{iso2: 'TW'}, value: '+886'},
  {label: 'Maldives', properties:{iso2: 'MV'}, value: '+960'},
  {label: 'Lebanon', properties:{iso2: 'LB'}, value: '+961'},
  {label: 'Jordan', properties:{iso2: 'JO'}, value: '+962'},
  {label: 'Syrian Arab Republic', properties:{iso2: 'SY'}, value: '+963'},
  {label: 'Iraq', properties:{iso2: 'IQ'}, value: '+964'},
  {label: 'Kuwait', properties:{iso2: 'KW'}, value: '+965'},
  {label: 'Saudi Arabia', properties:{iso2: 'SA'}, value: '+966'},
  {label: 'Yemen', properties:{iso2: 'YE'}, value: '+967'},
  {label: 'Oman', properties:{iso2: 'OM'}, value: '+968'},
  {label: 'Palestine', properties:{iso2: 'PS'}, value: '+970'},
  {label: 'United Arab Emirates', properties:{iso2: 'AE'}, value: '+971'},
  {label: 'Israel', properties:{iso2: 'IL'}, value: '+972'},
  {label: 'Bahrain', properties:{iso2: 'BH'}, value: '+973'},
  {label: 'Qatar', properties:{iso2: 'QA'}, value: '+974'},
  {label: 'Bhutan', properties:{iso2: 'BT'}, value: '+975'},
  {label: 'Mongolia', properties:{iso2: 'MN'}, value: '+976'},
  {label: 'Nepal', properties:{iso2: 'NP'}, value: '+977'},
  {label: 'Tajikistan', properties:{iso2: 'TJ'}, value: '+992'},
  {label: 'Turkmenistan', properties:{iso2: 'TM'}, value: '+993'},
  {label: 'Azerbaijan', properties:{iso2: 'AZ'}, value: '+994'},
  {label: 'Georgia', properties:{iso2: 'GE'}, value: '+995'},
  {label: 'Kyrgyzstan', properties:{iso2: 'KG'}, value: '+996'},
  {label: 'Uzbekistan', properties:{iso2: 'UZ'}, value: '+998'},
]