# This is a basic workflow to help you get started with Actions

name: Split code to individual repos

# Controls when the action will run. 
on:
  release:
    types: [created] 

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packages:
          - id: common
            deployKey: SVEADMIN_COMMON_GITHUB_DEPLOY_KEY
          - id: element
            deployKey: SVEADMIN_ELEMENT_GITHUB_DEPLOY_KEY
          - id: table
            deployKey: SVEADMIN_TABLE_GITHUB_DEPLOY_KEY
          - id: graph
            deployKey: SVEADMIN_GRAPH_GITHUB_DEPLOY_KEY
    name: Splitting ${{ matrix.packages.id }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout SVEADMIN monorepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate private key - ${{ matrix.packages.deployKey }}
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets[matrix.packages.deployKey] }}
          ssh-socket: /tmp/ssh_agent_${{ github.sha }}.sock
      - name: Updating ${{ matrix.packages.id }}
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'sveadmin/${{ matrix.packages.id }}'
          path: '${{ matrix.packages.id }}'
          force: true 
          tag: true
