/**
 * Flags provded by Flag Icons https://github.com/lipis/flag-icons/tree/main
 */
export const countryOptions = [
  {label: 'Andorra', properties:{iso2:'AD', iso3: 'AND', country: true, flag:'ad'}, value: 'AD'},
  {label: 'United Arab Emirates', properties:{iso2:'AE', iso3: 'ARE', country: true, flag:'ae'}, value: 'AE'},
  {label: 'Afghanistan', properties:{iso2:'AF', iso3: 'AFG', country: true, flag:'af'}, value: 'AF'},
  {label: 'Antigua and Barbuda', properties:{iso2:'AG', iso3: 'ATG', country: true, flag:'ag'}, value: 'AG'},
  {label: 'Anguilla', properties:{iso2:'AI', iso3: 'AIA', country: true, flag:'ai'}, value: 'AI'},
  {label: 'Albania', properties:{iso2:'AL', iso3: 'ALB', country: true, flag:'al'}, value: 'AL'},
  {label: 'Armenia', properties:{iso2:'AM', iso3: 'ARM', country: true, flag:'am'}, value: 'AM'},
  {label: 'Angola', properties:{iso2:'AO', iso3: 'AGO', country: true, flag:'ao'}, value: 'AO'},
  {label: 'Antarctica', properties:{iso2:'AQ', iso3: 'ATA', country: true, flag:'aq'}, value: 'AQ'},
  {label: 'Argentina', properties:{iso2:'AR', iso3: 'ARG', country: true, flag:'ar'}, value: 'AR'},
  {label: 'American Samoa', properties:{iso2:'AS', iso3: 'ASM', country: true, flag:'as'}, value: 'AS'},
  {label: 'Austria', properties:{iso2:'AT', iso3: 'AUT', country: true, flag:'at'}, value: 'AT'},
  {label: 'Australia', properties:{iso2:'AU', iso3: 'AUS', country: true, flag:'au'}, value: 'AU'},
  {label: 'Aruba', properties:{iso2:'AW', iso3: 'ABW', country: true, flag:'aw'}, value: 'AW'},
  {label: 'Åland Islands', properties:{iso2:'AX', iso3: 'ALA', country: true, flag:'ax'}, value: 'AX'},
  {label: 'Azerbaijan', properties:{iso2:'AZ', iso3: 'AZE', country: true, flag:'az'}, value: 'AZ'},
  {label: 'Bosnia and Herzegovina', properties:{iso2:'BA', iso3: 'BIH', country: true, flag:'ba'}, value: 'BA'},
  {label: 'Barbados', properties:{iso2:'BB', iso3: 'BRB', country: true, flag:'bb'}, value: 'BB'},
  {label: 'Bangladesh', properties:{iso2:'BD', iso3: 'BGD', country: true, flag:'bd'}, value: 'BD'},
  {label: 'Belgium', properties:{iso2:'BE', iso3: 'BEL', country: true, flag:'be'}, value: 'BE'},
  {label: 'Burkina Faso', properties:{iso2:'BF', iso3: 'BFA', country: true, flag:'bf'}, value: 'BF'},
  {label: 'Bulgaria', properties:{iso2:'BG', iso3: 'BGR', country: true, flag:'bg'}, value: 'BG'},
  {label: 'Bahrain', properties:{iso2:'BH', iso3: 'BHR', country: true, flag:'bh'}, value: 'BH'},
  {label: 'Burundi', properties:{iso2:'BI', iso3: 'BDI', country: true, flag:'bi'}, value: 'BI'},
  {label: 'Benin', properties:{iso2:'BJ', iso3: 'BEN', country: true, flag:'bj'}, value: 'BJ'},
  {label: 'Saint Barthélemy', properties:{iso2:'BL', iso3: 'BLM', country: true, flag:'bl'}, value: 'BL'},
  {label: 'Bermuda', properties:{iso2:'BM', iso3: 'BMU', country: true, flag:'bm'}, value: 'BM'},
  {label: 'Brunei Darussalam', properties:{iso2:'BN', iso3: 'BRN', country: true, flag:'bn'}, value: 'BN'},
  {label: 'Bolivia', properties:{iso2:'BO', iso3: 'BOL', country: true, flag:'bo'}, value: 'BO'},
  {label: 'Bonaire, Sint Eustatius and Saba', properties:{iso2:'BQ', iso3: 'BES', country: true, flag:'bq'}, value: 'BQ'},
  {label: 'Brazil', properties:{iso2:'BR', iso3: 'BRA', country: true, flag:'br'}, value: 'BR'},
  {label: 'Bahamas', properties:{iso2:'BS', iso3: 'BHS', country: true, flag:'bs'}, value: 'BS'},
  {label: 'Bhutan', properties:{iso2:'BT', iso3: 'BTN', country: true, flag:'bt'}, value: 'BT'},
  {label: 'Bouvet Island', properties:{iso2:'BV', iso3: 'BVT', country: true, flag:'bv'}, value: 'BV'},
  {label: 'Botswana', properties:{iso2:'BW', iso3: 'BWA', country: true, flag:'bw'}, value: 'BW'},
  {label: 'Belarus', properties:{iso2:'BY', iso3: 'BLR', country: true, flag:'by'}, value: 'BY'},
  {label: 'Belize', properties:{iso2:'BZ', iso3: 'BLZ', country: true, flag:'bz'}, value: 'BZ'},
  {label: 'Canada', properties:{iso2:'CA', iso3: 'CAN', country: true, flag:'ca'}, value: 'CA'},
  {label: 'Cocos (Keeling) Islands', properties:{iso2:'CC', iso3: 'CCK', country: true, flag:'cc'}, value: 'CC'},
  {label: 'Democratic Republic of the Congo', properties:{iso2:'CD', iso3: 'COD', country: true, flag:'cd'}, value: 'CD'},
  {label: 'Central African Republic', properties:{iso2:'CF', iso3: 'CAF', country: true, flag:'cf'}, value: 'CF'},
  {label: 'Congo', properties:{iso2:'CG', iso3: 'COG', country: true, flag:'cg'}, value: 'CG'},
  {label: 'Switzerland', properties:{iso2:'CH', iso3: 'CHE', country: true, flag:'ch'}, value: 'CH'},
  {label: 'Côte d\'Ivoire', properties:{iso2:'CI', iso3: 'CIV', country: true, flag:'ci'}, value: 'CI'},
  {label: 'Cook Islands', properties:{iso2:'CK', iso3: 'COK', country: true, flag:'ck'}, value: 'CK'},
  {label: 'Chile', properties:{iso2:'CL', iso3: 'CHL', country: true, flag:'cl'}, value: 'CL'},
  {label: 'Cameroon', properties:{iso2:'CM', iso3: 'CMR', country: true, flag:'cm'}, value: 'CM'},
  {label: 'China', properties:{iso2:'CN', iso3: 'CHN', country: true, flag:'cn'}, value: 'CN'},
  {label: 'Colombia', properties:{iso2:'CO', iso3: 'COL', country: true, flag:'co'}, value: 'CO'},
  {label: 'Costa Rica', properties:{iso2:'CR', iso3: 'CRI', country: true, flag:'cr'}, value: 'CR'},
  {label: 'Cuba', properties:{iso2:'CU', iso3: 'CUB', country: true, flag:'cu'}, value: 'CU'},
  {label: 'Cabo Verde', properties:{iso2:'CV', iso3: 'CPV', country: true, flag:'cv'}, value: 'CV'},
  {label: 'Curaçao', properties:{iso2:'CW', iso3: 'CUW', country: true, flag:'cw'}, value: 'CW'},
  {label: 'Christmas Island', properties:{iso2:'CX', iso3: 'CXR', country: true, flag:'cx'}, value: 'CX'},
  {label: 'Cyprus', properties:{iso2:'CY', iso3: 'CYP', country: true, flag:'cy'}, value: 'CY'},
  {label: 'Czechia', properties:{iso2:'CZ', iso3: 'CZE', country: true, flag:'cz'}, value: 'CZ'},
  {label: 'Germany', properties:{iso2:'DE', iso3: 'DEU', country: true, flag:'de'}, value: 'DE'},
  {label: 'Djibouti', properties:{iso2:'DJ', iso3: 'DJI', country: true, flag:'dj'}, value: 'DJ'},
  {label: 'Denmark', properties:{iso2:'DK', iso3: 'DNK', country: true, flag:'dk'}, value: 'DK'},
  {label: 'Dominica', properties:{iso2:'DM', iso3: 'DMA', country: true, flag:'dm'}, value: 'DM'},
  {label: 'Dominican Republic', properties:{iso2:'DO', iso3: 'DOM', country: true, flag:'do'}, value: 'DO'},
  {label: 'Algeria', properties:{iso2:'DZ', iso3: 'DZA', country: true, flag:'dz'}, value: 'DZ'},
  {label: 'Ecuador', properties:{iso2:'EC', iso3: 'ECU', country: true, flag:'ec'}, value: 'EC'},
  {label: 'Estonia', properties:{iso2:'EE', iso3: 'EST', country: true, flag:'ee'}, value: 'EE'},
  {label: 'Egypt', properties:{iso2:'EG', iso3: 'EGY', country: true, flag:'eg'}, value: 'EG'},
  {label: 'Western Sahara', properties:{iso2:'EH', iso3: 'ESH', country: true, flag:'eh'}, value: 'EH'},
  {label: 'Eritrea', properties:{iso2:'ER', iso3: 'ERI', country: true, flag:'er'}, value: 'ER'},
  {label: 'Spain', properties:{iso2:'ES', iso3: 'ESP', country: true, flag:'es'}, value: 'ES'},
  {label: 'Ethiopia', properties:{iso2:'ET', iso3: 'ETH', country: true, flag:'et'}, value: 'ET'},
  {label: 'Finland', properties:{iso2:'FI', iso3: 'FIN', country: true, flag:'fi'}, value: 'FI'},
  {label: 'Fiji', properties:{iso2:'FJ', iso3: 'FJI', country: true, flag:'fj'}, value: 'FJ'},
  {label: 'Falkland Islands', properties:{iso2:'FK', iso3: 'FLK', country: true, flag:'fk'}, value: 'FK'},
  {label: 'Micronesia', properties:{iso2:'FM', iso3: 'FSM', country: true, flag:'fm'}, value: 'FM'},
  {label: 'Faroe Islands', properties:{iso2:'FO', iso3: 'FRO', country: true, flag:'fo'}, value: 'FO'},
  {label: 'France', properties:{iso2:'FR', iso3: 'FRA', country: true, flag:'fr'}, value: 'FR'},
  {label: 'Gabon', properties:{iso2:'GA', iso3: 'GAB', country: true, flag:'ga'}, value: 'GA'},
  {label: 'United Kingdom', properties:{iso2:'GB', iso3: 'GBR', country: true, flag:'gb'}, value: 'GB'},
  {label: 'Grenada', properties:{iso2:'GD', iso3: 'GRD', country: true, flag:'gd'}, value: 'GD'},
  {label: 'Georgia', properties:{iso2:'GE', iso3: 'GEO', country: true, flag:'ge'}, value: 'GE'},
  {label: 'French Guiana', properties:{iso2:'GF', iso3: 'GUF', country: true, flag:'gf'}, value: 'GF'},
  {label: 'Guernsey', properties:{iso2:'GG', iso3: 'GGY', country: true, flag:'gg'}, value: 'GG'},
  {label: 'Ghana', properties:{iso2:'GH', iso3: 'GHA', country: true, flag:'gh'}, value: 'GH'},
  {label: 'Gibraltar', properties:{iso2:'GI', iso3: 'GIB', country: true, flag:'gi'}, value: 'GI'},
  {label: 'Greenland', properties:{iso2:'GL', iso3: 'GRL', country: true, flag:'gl'}, value: 'GL'},
  {label: 'Gambia', properties:{iso2:'GM', iso3: 'GMB', country: true, flag:'gm'}, value: 'GM'},
  {label: 'Guinea', properties:{iso2:'GN', iso3: 'GIN', country: true, flag:'gn'}, value: 'GN'},
  {label: 'Guadeloupe', properties:{iso2:'GP', iso3: 'GLP', country: true, flag:'gp'}, value: 'GP'},
  {label: 'Equatorial Guinea', properties:{iso2:'GQ', iso3: 'GNQ', country: true, flag:'gq'}, value: 'GQ'},
  {label: 'Greece', properties:{iso2:'GR', iso3: 'GRC', country: true, flag:'gr'}, value: 'GR'},
  {label: 'South Georgia and the South Sandwich Islands', properties:{iso2:'GS', iso3: 'SGS', country: true, flag:'gs'}, value: 'GS'},
  {label: 'Guatemala', properties:{iso2:'GT', iso3: 'GTM', country: true, flag:'gt'}, value: 'GT'},
  {label: 'Guam', properties:{iso2:'GU', iso3: 'GUM', country: true, flag:'gu'}, value: 'GU'},
  {label: 'Guinea-Bissau', properties:{iso2:'GW', iso3: 'GNB', country: true, flag:'gw'}, value: 'GW'},
  {label: 'Guyana', properties:{iso2:'GY', iso3: 'GUY', country: true, flag:'gy'}, value: 'GY'},
  {label: 'Hong Kong', properties:{iso2:'HK', iso3: 'HKG', country: true, flag:'hk'}, value: 'HK'},
  {label: 'Heard Island and McDonald Islands', properties:{iso2:'HM', iso3: 'HMD', country: true, flag:'hm'}, value: 'HM'},
  {label: 'Honduras', properties:{iso2:'HN', iso3: 'HND', country: true, flag:'hn'}, value: 'HN'},
  {label: 'Croatia', properties:{iso2:'HR', iso3: 'HRV', country: true, flag:'hr'}, value: 'HR'},
  {label: 'Haiti', properties:{iso2:'HT', iso3: 'HTI', country: true, flag:'ht'}, value: 'HT'},
  {label: 'Hungary', properties:{iso2:'HU', iso3: 'HUN', country: true, flag:'hu'}, value: 'HU'},
  {label: 'Indonesia', properties:{iso2:'ID', iso3: 'IDN', country: true, flag:'id'}, value: 'ID'},
  {label: 'Ireland', properties:{iso2:'IE', iso3: 'IRL', country: true, flag:'ie'}, value: 'IE'},
  {label: 'Israel', properties:{iso2:'IL', iso3: 'ISR', country: true, flag:'il'}, value: 'IL'},
  {label: 'Isle of Man', properties:{iso2:'IM', iso3: 'IMN', country: true, flag:'im'}, value: 'IM'},
  {label: 'India', properties:{iso2:'IN', iso3: 'IND', country: true, flag:'in'}, value: 'IN'},
  {label: 'British Indian Ocean Territory', properties:{iso2:'IO', iso3: 'IOT', country: true, flag:'io'}, value: 'IO'},
  {label: 'Iraq', properties:{iso2:'IQ', iso3: 'IRQ', country: true, flag:'iq'}, value: 'IQ'},
  {label: 'Iran', properties:{iso2:'IR', iso3: 'IRN', country: true, flag:'ir'}, value: 'IR'},
  {label: 'Iceland', properties:{iso2:'IS', iso3: 'ISL', country: true, flag:'is'}, value: 'IS'},
  {label: 'Italy', properties:{iso2:'IT', iso3: 'ITA', country: true, flag:'it'}, value: 'IT'},
  {label: 'Jersey', properties:{iso2:'JE', iso3: 'JEY', country: true, flag:'je'}, value: 'JE'},
  {label: 'Jamaica', properties:{iso2:'JM', iso3: 'JAM', country: true, flag:'jm'}, value: 'JM'},
  {label: 'Jordan', properties:{iso2:'JO', iso3: 'JOR', country: true, flag:'jo'}, value: 'JO'},
  {label: 'Japan', properties:{iso2:'JP', iso3: 'JPN', country: true, flag:'jp'}, value: 'JP'},
  {label: 'Kenya', properties:{iso2:'KE', iso3: 'KEN', country: true, flag:'ke'}, value: 'KE'},
  {label: 'Kyrgyzstan', properties:{iso2:'KG', iso3: 'KGZ', country: true, flag:'kg'}, value: 'KG'},
  {label: 'Cambodia', properties:{iso2:'KH', iso3: 'KHM', country: true, flag:'kh'}, value: 'KH'},
  {label: 'Kiribati', properties:{iso2:'KI', iso3: 'KIR', country: true, flag:'ki'}, value: 'KI'},
  {label: 'Comoros', properties:{iso2:'KM', iso3: 'COM', country: true, flag:'km'}, value: 'KM'},
  {label: 'Saint Kitts and Nevis', properties:{iso2:'KN', iso3: 'KNA', country: true, flag:'kn'}, value: 'KN'},
  {label: 'Democratic People\'s Republic of Korea', properties:{iso2:'KP', iso3: 'PRK', country: true, flag:'kp'}, value: 'KP'},
  {label: 'South Korea', properties:{iso2:'KR', iso3: 'KOR', country: true, flag:'kr'}, value: 'KR'},
  {label: 'Kuwait', properties:{iso2:'KW', iso3: 'KWT', country: true, flag:'kw'}, value: 'KW'},
  {label: 'Cayman Islands', properties:{iso2:'KY', iso3: 'CYM', country: true, flag:'ky'}, value: 'KY'},
  {label: 'Kazakhstan', properties:{iso2:'KZ', iso3: 'KAZ', country: true, flag:'kz'}, value: 'KZ'},
  {label: 'Laos', properties:{iso2:'LA', iso3: 'LAO', country: true, flag:'la'}, value: 'LA'},
  {label: 'Lebanon', properties:{iso2:'LB', iso3: 'LBN', country: true, flag:'lb'}, value: 'LB'},
  {label: 'Saint Lucia', properties:{iso2:'LC', iso3: 'LCA', country: true, flag:'lc'}, value: 'LC'},
  {label: 'Liechtenstein', properties:{iso2:'LI', iso3: 'LIE', country: true, flag:'li'}, value: 'LI'},
  {label: 'Sri Lanka', properties:{iso2:'LK', iso3: 'LKA', country: true, flag:'lk'}, value: 'LK'},
  {label: 'Liberia', properties:{iso2:'LR', iso3: 'LBR', country: true, flag:'lr'}, value: 'LR'},
  {label: 'Lesotho', properties:{iso2:'LS', iso3: 'LSO', country: true, flag:'ls'}, value: 'LS'},
  {label: 'Lithuania', properties:{iso2:'LT', iso3: 'LTU', country: true, flag:'lt'}, value: 'LT'},
  {label: 'Luxembourg', properties:{iso2:'LU', iso3: 'LUX', country: true, flag:'lu'}, value: 'LU'},
  {label: 'Latvia', properties:{iso2:'LV', iso3: 'LVA', country: true, flag:'lv'}, value: 'LV'},
  {label: 'Libya', properties:{iso2:'LY', iso3: 'LBY', country: true, flag:'ly'}, value: 'LY'},
  {label: 'Morocco', properties:{iso2:'MA', iso3: 'MAR', country: true, flag:'ma'}, value: 'MA'},
  {label: 'Monaco', properties:{iso2:'MC', iso3: 'MCO', country: true, flag:'mc'}, value: 'MC'},
  {label: 'Moldova', properties:{iso2:'MD', iso3: 'MDA', country: true, flag:'md'}, value: 'MD'},
  {label: 'Montenegro', properties:{iso2:'ME', iso3: 'MNE', country: true, flag:'me'}, value: 'ME'},
  {label: 'Saint Martin', properties:{iso2:'MF', iso3: 'MAF', country: true, flag:'mf'}, value: 'MF'},
  {label: 'Madagascar', properties:{iso2:'MG', iso3: 'MDG', country: true, flag:'mg'}, value: 'MG'},
  {label: 'Marshall Islands', properties:{iso2:'MH', iso3: 'MHL', country: true, flag:'mh'}, value: 'MH'},
  {label: 'North Macedonia', properties:{iso2:'MK', iso3: 'MKD', country: true, flag:'mk'}, value: 'MK'},
  {label: 'Mali', properties:{iso2:'ML', iso3: 'MLI', country: true, flag:'ml'}, value: 'ML'},
  {label: 'Myanmar', properties:{iso2:'MM', iso3: 'MMR', country: true, flag:'mm'}, value: 'MM'},
  {label: 'Mongolia', properties:{iso2:'MN', iso3: 'MNG', country: true, flag:'mn'}, value: 'MN'},
  {label: 'Macao', properties:{iso2:'MO', iso3: 'MAC', country: true, flag:'mo'}, value: 'MO'},
  {label: 'Northern Mariana Islands', properties:{iso2:'MP', iso3: 'MNP', country: true, flag:'mp'}, value: 'MP'},
  {label: 'Martinique', properties:{iso2:'MQ', iso3: 'MTQ', country: true, flag:'mq'}, value: 'MQ'},
  {label: 'Mauritania', properties:{iso2:'MR', iso3: 'MRT', country: true, flag:'mr'}, value: 'MR'},
  {label: 'Montserrat', properties:{iso2:'MS', iso3: 'MSR', country: true, flag:'ms'}, value: 'MS'},
  {label: 'Malta', properties:{iso2:'MT', iso3: 'MLT', country: true, flag:'mt'}, value: 'MT'},
  {label: 'Mauritius', properties:{iso2:'MU', iso3: 'MUS', country: true, flag:'mu'}, value: 'MU'},
  {label: 'Maldives', properties:{iso2:'MV', iso3: 'MDV', country: true, flag:'mv'}, value: 'MV'},
  {label: 'Malawi', properties:{iso2:'MW', iso3: 'MWI', country: true, flag:'mw'}, value: 'MW'},
  {label: 'Mexico', properties:{iso2:'MX', iso3: 'MEX', country: true, flag:'mx'}, value: 'MX'},
  {label: 'Malaysia', properties:{iso2:'MY', iso3: 'MYS', country: true, flag:'my'}, value: 'MY'},
  {label: 'Mozambique', properties:{iso2:'MZ', iso3: 'MOZ', country: true, flag:'mz'}, value: 'MZ'},
  {label: 'Namibia', properties:{iso2:'NA', iso3: 'NAM', country: true, flag:'na'}, value: 'NA'},
  {label: 'New Caledonia', properties:{iso2:'NC', iso3: 'NCL', country: true, flag:'nc'}, value: 'NC'},
  {label: 'Niger', properties:{iso2:'NE', iso3: 'NER', country: true, flag:'ne'}, value: 'NE'},
  {label: 'Norfolk Island', properties:{iso2:'NF', iso3: 'NFK', country: true, flag:'nf'}, value: 'NF'},
  {label: 'Nigeria', properties:{iso2:'NG', iso3: 'NGA', country: true, flag:'ng'}, value: 'NG'},
  {label: 'Nicaragua', properties:{iso2:'NI', iso3: 'NIC', country: true, flag:'ni'}, value: 'NI'},
  {label: 'Netherlands', properties:{iso2:'NL', iso3: 'NLD', country: true, flag:'nl'}, value: 'NL'},
  {label: 'Norway', properties:{iso2:'NO', iso3: 'NOR', country: true, flag:'no'}, value: 'NO'},
  {label: 'Nepal', properties:{iso2:'NP', iso3: 'NPL', country: true, flag:'np'}, value: 'NP'},
  {label: 'Nauru', properties:{iso2:'NR', iso3: 'NRU', country: true, flag:'nr'}, value: 'NR'},
  {label: 'Niue', properties:{iso2:'NU', iso3: 'NIU', country: true, flag:'nu'}, value: 'NU'},
  {label: 'New Zealand', properties:{iso2:'NZ', iso3: 'NZL', country: true, flag:'nz'}, value: 'NZ'},
  {label: 'Oman', properties:{iso2:'OM', iso3: 'OMN', country: true, flag:'om'}, value: 'OM'},
  {label: 'Panama', properties:{iso2:'PA', iso3: 'PAN', country: true, flag:'pa'}, value: 'PA'},
  {label: 'Peru', properties:{iso2:'PE', iso3: 'PER', country: true, flag:'pe'}, value: 'PE'},
  {label: 'French Polynesia', properties:{iso2:'PF', iso3: 'PYF', country: true, flag:'pf'}, value: 'PF'},
  {label: 'Papua New Guinea', properties:{iso2:'PG', iso3: 'PNG', country: true, flag:'pg'}, value: 'PG'},
  {label: 'Philippines', properties:{iso2:'PH', iso3: 'PHL', country: true, flag:'ph'}, value: 'PH'},
  {label: 'Pakistan', properties:{iso2:'PK', iso3: 'PAK', country: true, flag:'pk'}, value: 'PK'},
  {label: 'Poland', properties:{iso2:'PL', iso3: 'POL', country: true, flag:'pl'}, value: 'PL'},
  {label: 'Saint Pierre and Miquelon', properties:{iso2:'PM', iso3: 'SPM', country: true, flag:'pm'}, value: 'PM'},
  {label: 'Pitcairn', properties:{iso2:'PN', iso3: 'PCN', country: true, flag:'pn'}, value: 'PN'},
  {label: 'Puerto Rico', properties:{iso2:'PR', iso3: 'PRI', country: true, flag:'pr'}, value: 'PR'},
  {label: 'Palestine', properties:{iso2:'PS', iso3: 'PSE', country: true, flag:'ps'}, value: 'PS'},
  {label: 'Portugal', properties:{iso2:'PT', iso3: 'PRT', country: true, flag:'pt'}, value: 'PT'},
  {label: 'Palau', properties:{iso2:'PW', iso3: 'PLW', country: true, flag:'pw'}, value: 'PW'},
  {label: 'Paraguay', properties:{iso2:'PY', iso3: 'PRY', country: true, flag:'py'}, value: 'PY'},
  {label: 'Qatar', properties:{iso2:'QA', iso3: 'QAT', country: true, flag:'qa'}, value: 'QA'},
  {label: 'Réunion', properties:{iso2:'RE', iso3: 'REU', country: true, flag:'re'}, value: 'RE'},
  {label: 'Romania', properties:{iso2:'RO', iso3: 'ROU', country: true, flag:'ro'}, value: 'RO'},
  {label: 'Serbia', properties:{iso2:'RS', iso3: 'SRB', country: true, flag:'rs'}, value: 'RS'},
  {label: 'Russian Federation', properties:{iso2:'RU', iso3: 'RUS', country: true, flag:'ru'}, value: 'RU'},
  {label: 'Rwanda', properties:{iso2:'RW', iso3: 'RWA', country: true, flag:'rw'}, value: 'RW'},
  {label: 'Saudi Arabia', properties:{iso2:'SA', iso3: 'SAU', country: true, flag:'sa'}, value: 'SA'},
  {label: 'Solomon Islands', properties:{iso2:'SB', iso3: 'SLB', country: true, flag:'sb'}, value: 'SB'},
  {label: 'Seychelles', properties:{iso2:'SC', iso3: 'SYC', country: true, flag:'sc'}, value: 'SC'},
  {label: 'Sudan', properties:{iso2:'SD', iso3: 'SDN', country: true, flag:'sd'}, value: 'SD'},
  {label: 'Sweden', properties:{iso2:'SE', iso3: 'SWE', country: true, flag:'se'}, value: 'SE'},
  {label: 'Singapore', properties:{iso2:'SG', iso3: 'SGP', country: true, flag:'sg'}, value: 'SG'},
  {label: 'Saint Helena, Ascension and Tristan da Cunha', properties:{iso2:'SH', iso3: 'SHN', country: true, flag:'sh'}, value: 'SH'},
  {label: 'Slovenia', properties:{iso2:'SI', iso3: 'SVN', country: true, flag:'si'}, value: 'SI'},
  {label: 'Svalbard and Jan Mayen', properties:{iso2:'SJ', iso3: 'SJM', country: true, flag:'sj'}, value: 'SJ'},
  {label: 'Slovakia', properties:{iso2:'SK', iso3: 'SVK', country: true, flag:'sk'}, value: 'SK'},
  {label: 'Sierra Leone', properties:{iso2:'SL', iso3: 'SLE', country: true, flag:'sl'}, value: 'SL'},
  {label: 'San Marino', properties:{iso2:'SM', iso3: 'SMR', country: true, flag:'sm'}, value: 'SM'},
  {label: 'Senegal', properties:{iso2:'SN', iso3: 'SEN', country: true, flag:'sn'}, value: 'SN'},
  {label: 'Somalia', properties:{iso2:'SO', iso3: 'SOM', country: true, flag:'so'}, value: 'SO'},
  {label: 'Suriname', properties:{iso2:'SR', iso3: 'SUR', country: true, flag:'sr'}, value: 'SR'},
  {label: 'South Sudan', properties:{iso2:'SS', iso3: 'SSD', country: true, flag:'ss'}, value: 'SS'},
  {label: 'Sao Tome and Principe', properties:{iso2:'ST', iso3: 'STP', country: true, flag:'st'}, value: 'ST'},
  {label: 'El Salvador', properties:{iso2:'SV', iso3: 'SLV', country: true, flag:'sv'}, value: 'SV'},
  {label: 'Sint Maarten', properties:{iso2:'SX', iso3: 'SXM', country: true, flag:'sx'}, value: 'SX'},
  {label: 'Syrian Arab Republic', properties:{iso2:'SY', iso3: 'SYR', country: true, flag:'sy'}, value: 'SY'},
  {label: 'Eswatini', properties:{iso2:'SZ', iso3: 'SWZ', country: true, flag:'sz'}, value: 'SZ'},
  {label: 'Turks and Caicos Islands', properties:{iso2:'TC', iso3: 'TCA', country: true, flag:'tc'}, value: 'TC'},
  {label: 'Chad', properties:{iso2:'TD', iso3: 'TCD', country: true, flag:'td'}, value: 'TD'},
  {label: 'French Southern Territories', properties:{iso2:'TF', iso3: 'ATF', country: true, flag:'tf'}, value: 'TF'},
  {label: 'Togo', properties:{iso2:'TG', iso3: 'TGO', country: true, flag:'tg'}, value: 'TG'},
  {label: 'Thailand', properties:{iso2:'TH', iso3: 'THA', country: true, flag:'th'}, value: 'TH'},
  {label: 'Tajikistan', properties:{iso2:'TJ', iso3: 'TJK', country: true, flag:'tj'}, value: 'TJ'},
  {label: 'Tokelau', properties:{iso2:'TK', iso3: 'TKL', country: true, flag:'tk'}, value: 'TK'},
  {label: 'Timor-Leste', properties:{iso2:'TL', iso3: 'TLS', country: true, flag:'tl'}, value: 'TL'},
  {label: 'Turkmenistan', properties:{iso2:'TM', iso3: 'TKM', country: true, flag:'tm'}, value: 'TM'},
  {label: 'Tunisia', properties:{iso2:'TN', iso3: 'TUN', country: true, flag:'tn'}, value: 'TN'},
  {label: 'Tonga', properties:{iso2:'TO', iso3: 'TON', country: true, flag:'to'}, value: 'TO'},
  {label: 'Turkey', properties:{iso2:'TR', iso3: 'TUR', country: true, flag:'tr'}, value: 'TR'},
  {label: 'Trinidad and Tobago', properties:{iso2:'TT', iso3: 'TTO', country: true, flag:'tt'}, value: 'TT'},
  {label: 'Tuvalu', properties:{iso2:'TV', iso3: 'TUV', country: true, flag:'tv'}, value: 'TV'},
  {label: 'Taiwan', properties:{iso2:'TW', iso3: 'TWN', country: true, flag:'tw'}, value: 'TW'},
  {label: 'Tanzania', properties:{iso2:'TZ', iso3: 'TZA', country: true, flag:'tz'}, value: 'TZ'},
  {label: 'Ukraine', properties:{iso2:'UA', iso3: 'UKR', country: true, flag:'ua'}, value: 'UA'},
  {label: 'Uganda', properties:{iso2:'UG', iso3: 'UGA', country: true, flag:'ug'}, value: 'UG'},
  {label: 'United States Minor Outlying Islands', properties:{iso2:'UM', iso3: 'UMI', country: true, flag:'um'}, value: 'UM'},
  {label: 'United States of America', properties:{iso2:'US', iso3: 'USA', country: true, flag:'us'}, value: 'US'},
  {label: 'Uruguay', properties:{iso2:'UY', iso3: 'URY', country: true, flag:'uy'}, value: 'UY'},
  {label: 'Uzbekistan', properties:{iso2:'UZ', iso3: 'UZB', country: true, flag:'uz'}, value: 'UZ'},
  {label: 'Holy See', properties:{iso2:'VA', iso3: 'VAT', country: true, flag:'va'}, value: 'VA'},
  {label: 'Saint Vincent and the Grenadines', properties:{iso2:'VC', iso3: 'VCT', country: true, flag:'vc'}, value: 'VC'},
  {label: 'Venezuela', properties:{iso2:'VE', iso3: 'VEN', country: true, flag:'ve'}, value: 'VE'},
  {label: 'British Virgin Islands', properties:{iso2:'VG', iso3: 'VGB', country: true, flag:'vg'}, value: 'VG'},
  {label: 'Virgin Islands', properties:{iso2:'VI', iso3: 'VIR', country: true, flag:'vi'}, value: 'VI'},
  {label: 'Viet Nam', properties:{iso2:'VN', iso3: 'VNM', country: true, flag:'vn'}, value: 'VN'},
  {label: 'Vanuatu', properties:{iso2:'VU', iso3: 'VUT', country: true, flag:'vu'}, value: 'VU'},
  {label: 'Wallis and Futuna', properties:{iso2:'WF', iso3: 'WLF', country: true, flag:'wf'}, value: 'WF'},
  {label: 'Samoa', properties:{iso2:'WS', iso3: 'WSM', country: true, flag:'ws'}, value: 'WS'},
  {label: 'Yemen', properties:{iso2:'YE', iso3: 'YEM', country: true, flag:'ye'}, value: 'YE'},
  {label: 'Mayotte', properties:{iso2:'YT', iso3: 'MYT', country: true, flag:'yt'}, value: 'YT'},
  {label: 'South Africa', properties:{iso2:'ZA', iso3: 'ZAF', country: true, flag:'za'}, value: 'ZA'},
  {label: 'Zambia', properties:{iso2:'ZM', iso3: 'ZMB', country: true, flag:'zm'}, value: 'ZM'},
  {label: 'Zimbabwe', properties:{iso2:'ZW', iso3: 'ZWE', country: true, flag:'zw'}, value: 'ZW'},
  {label: 'League of Arab States', properties:{iso2:'', iso3: '', country: false, flag:'arab'}, value: 'ARAB'},
  {label: 'Association of Southeast Asian Nations', properties:{iso2:'', iso3: '', country: false, flag:'asean'}, value: 'ASEAN'},
  {label: 'Central European Free Trade Agreement', properties:{iso2:'', iso3: '', country: false, flag:'cefta'}, value: 'CEFTA'},
  {label: 'Clipperton Island', properties:{iso2:'', iso3: '', country: false, flag:'cp'}, value: 'CP'},
  {label: 'Diego Garcia', properties:{iso2:'', iso3: '', country: false, flag:'dg'}, value: 'DG'},
  {label: 'East African Community', properties:{iso2:'', iso3: '', country: false, flag:'eac'}, value: 'EAC'},
  {label: 'Catalonia', properties:{iso2:'', iso3: '', country: false, flag:'es-ct'}, value: 'ES-CT'},
  {label: 'Galicia', properties:{iso2:'', iso3: '', country: false, flag:'es-ga'}, value: 'ES-GA'},
  {label: 'Basque Country', properties:{iso2:'', iso3: '', country: false, flag:'es-pv'}, value: 'ES-PV'},
  {label: 'European Union', properties:{iso2:'', iso3: '', country: false, flag:'eu'}, value: 'EU'},
  {label: 'England', properties:{iso2:'', iso3: '', country: false, flag:'gb-eng'}, value: 'GB-ENG'},
  {label: 'Northern Ireland', properties:{iso2:'', iso3: '', country: false, flag:'gb-nir'}, value: 'GB-NIR'},
  {label: 'Scotland', properties:{iso2:'', iso3: '', country: false, flag:'gb-sct'}, value: 'GB-SCT'},
  {label: 'Wales', properties:{iso2:'', iso3: '', country: false, flag:'gb-wls'}, value: 'GB-WLS'},
  {label: 'Canary Islands', properties:{iso2:'', iso3: '', country: false, flag:'ic'}, value: 'IC'},
  {label: 'Pacific Community', properties:{iso2:'', iso3: '', country: false, flag:'pc'}, value: 'PC'},
  {label: 'Ascension Island', properties:{iso2:'', iso3: '', country: false, flag:'sh-ac'}, value: 'SH-AC'},
  {label: 'Saint Helena', properties:{iso2:'', iso3: '', country: false, flag:'sh-hl'}, value: 'SH-HL'},
  {label: 'Tristan de Cunha', properties:{iso2:'', iso3: '', country: false, flag:'sh-ta'}, value: 'SH-TA'},
  {label: 'United Nations', properties:{iso2:'', iso3: '', country: false, flag:'un'}, value: 'UN'},
  {label: 'Kosovo', properties:{iso2:'', iso3: '', country: false, flag:'xk'}, value: 'XK'},
]